### ISSUE TITLE
Lua Error when opening the Map or doing anything with the Map

### ISSUE THREAD

**Issue by grimclaw-draven** [Questie/Questie#5193] opened 2023-11-08 16:16 UTC
## Bug description´

When doing anything like getting in the game, opening the map or switching the map, I get this error.
All Icons and stuff is still displayed but getting a thrown bug every 5 seconds kinda sucks and makes this addon currently unusable.

Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
Time: Wed Nov  8 17:10:35 2023
Count: 1
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1817: in function `UpdateHeight'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1742: in function `UpdateFormatting'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1651: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1692: in function `func'
[string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals: self = <table> {
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2162
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:502
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:553
 IsTrackedAchievement = <function> defined =[C]:-1
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1758
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:318
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2026
 started = true
 alreadyHooked = true
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2071
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2196
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:75
 GetNumTrackedAchievements = <function> defined =[C]:-1
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:514
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:463
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2147
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2004
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2050
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:438
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1698
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:364
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1888
 GetNumQuestWatches = <function> defined =[C]:-1
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:386
 IsQuestWatched = <function> defined =[C]:-1
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:561
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1801
 alreadyHookedSecure = true
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:544
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2203
 private = <table> {
 }
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:532
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:288
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:271
}
trackerHeaderFrameHeight = 52.000025
trackerHeightByRatio = 426.666687
trackerHeightByManual = 0
trackerHeight

## Screenshots
No screenshot but error is fully pasted above.

## Questie & WoW version
Questie version 8.10.10, showing in WowUp as up to date.
WoW Wotlk latest version

**Comment by BreakBB** [comment] 2023-11-08 16:26
Can you also post the output of the following commands:

`/dump QuestieLoader:ImportModule("TrackerLinePool").GetFirstLine():GetTop()`
`/dump QuestieLoader:ImportModule("TrackerLinePool").GetCurrentLine():GetBottom()`

**Comment by BreakBB** [comment] 2023-11-08 16:27
This is also related/a duplicate of #5058

**Comment by grimclaw-draven** [comment] 2023-11-08 17:15
It seems like it is fixed already, dunno how it is possible.
I struggled with it for 2h and even deinstalled all addons and restarted my pc and nothing happened.

But now after 15 min of clicking away the error, I cant replicateit anymore.

**Closed** 2023-11-08 17:47 UTC
Labels: Bug
