### ISSUE TITLE
weird av error

### ISSUE THREAD

**Issue by Tweakjeezy** [Questie/Questie#4975] opened 2023-06-18 19:42 UTC
## Bug description

Message: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:746: attempt to get length of a nil value
Time: Sun Jun 18 14:40:30 2023
Count: 7
Stack: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:746: attempt to get length of a nil value
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:746: in function `AddFinisher'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1245: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:656: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:483: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:480>

Locals: 
## Questie & WoW version

whenever i enter an av i get the above lua error. o copied the entire string

**Comment by Cabro** [comment] 2023-06-18 19:44
What quests do you have in Quest Log?

**Comment by Tweakjeezy** [comment] 2023-06-18 19:45
![image](https://github.com/Questie/Questie/assets/137001640/872067cb-3344-4233-b1fb-780544e54443)

**Comment by Tweakjeezy** [comment] 2023-06-18 19:46
[image: image.png]
i did delete enemy booty the av quest just during this game

**Comment by Cabro** [comment] 2023-06-18 20:13
There's nothing wrong with the quest database, i checked all your quests. All objectives are there. Must be some weird race condition here, so I'll let this to the higherups :)
PS - i changed the tooltip for the devilsaurs for Toxic Test

**Comment by Dyaxler** [comment] 2023-06-21 20:57
Duplicate of #4972

**Closed** 2023-06-25 20:53 UTC
Labels: Bug, Module - Quest
