### ISSUE TITLE
[[74] Seared Scourge (12029)] - does not show troll location on the map

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4284] opened 2022-10-01 13:31 UTC
Should mark https://www.wowhead.com/wotlk/npc=26570/famished-scourge-troll

**Comment by Yttrium-tYcLief** [comment] 2022-10-01 17:44
Duplicate of #3757, and will be fixed with #4279

**Closed** 2022-10-01 23:08 UTC
Labels: Questie - Quest Issue, Data Correction
