### ISSUE TITLE
Getting Disconnected when running questie and leveling skills

### ISSUE THREAD

**Issue by Young-Zay** [Questie/Questie#4001] opened 2022-09-01 03:07 UTC
Hello,

Very weird issue that i've isolated to questie alone (turned all other addons off). When leveling up a weapon or profession, I will be dc-ed and have to reconnect constantly. After about 10 levels up if they are quick it will kick me. I can reproduce it easily, really not sure what could be happening. Thanks.

**Comment by Young-Zay** [comment] 2022-09-01 03:07
Oops, tried older version and version 7.0.1 on Wotlk pre patch. Same issue.

**Comment by Yttrium-tYcLief** [comment] 2022-09-01 05:59
Duplicate of #3987

**Comment by BreakBB** [comment] 2022-09-01 09:04
As @Yttrium-tYcLief this is a duplicated report. Check the other issue for more information.

**Closed** 2022-09-01 09:04 UTC
