### ISSUE TITLE
ERROR during initialization. Interface/AddOns/Questie/Modules/QuestieInit.lua:281:

### ISSUE THREAD

**Issue by Heyjackand** [Questie/Questie#6340] opened 2024-08-03 00:24 UTC
## Bug description

Error on launch. Does not load any questie. 

## Screenshots

![image](https://github.com/user-attachments/assets/c9fca6a4-5f29-4433-9702-970c54420e8b)

## Questie & WoW version

Classic Era

**Comment by BreakBB** [comment] 2024-08-03 00:26
Duplicate of #6334 

A fixed version was just released - https://github.com/Questie/Questie/releases/tag/v10.3.10

Blizzard randomly removed an UI element Questie relied on.

**Closed by BreakBB** 2024-08-03 00:26 UTC
Labels: Bug
