### ISSUE TITLE
Tracker Keeps Expanding Horizontaly

### ISSUE THREAD

**Issue by allcoast** [Questie/Questie#4110] opened 2022-09-12 19:52 UTC
## Bug description
When clicking on the pull icon in the lower right corner, the tracker will keep growing in size, width wise.

## Screenshots

![2022-09-12_15h51_46](https://user-images.githubusercontent.com/20448848/189743245-dfacfb35-eefd-4f94-953d-95c6067b9209.png)

**Comment by allcoast** [comment] 2022-09-12 19:54
Actually, i found that you can just click it.

**Comment by allcoast** [comment] 2022-09-12 20:02
or whenever an objective is updated, it keeps growing.

**Comment by jak-lawrence** [comment] 2022-09-13 10:52
I was having this issue - I went through and removed the addon and it's config from WTF, then reinstalled via Curseforge and it seems to be behaving normally now, so I'd recommend doing that. I think the curseforge client has a right-click option to easily deleting the settings files and reinstall the addon so that may also work.

**Comment by drejjmit** [comment] 2022-09-13 10:55
Are you on latest v7.1.1?

**Comment by jak-lawrence** [comment] 2022-09-13 11:02
Seems to only happen for me if I set the font size above 12. Still happening after purging settings and reinstalling via curseforge.

**Comment by allcoast** [comment] 2022-09-13 11:14
> 

Yes, I was on the latest version 7.1.1

**Comment by rafalss** [comment] 2022-09-13 12:40
Been having the same issues, but only when I change the actual font, not just the font size. When I only changed the font size and left it at the default Friz Quadrata TT, it is no longer expanding.

**Comment by Drac84** [comment] 2022-09-19 05:26
Bloating tracker frame still a bug in 7.1.2. 

- Reset addon and changed the font back to Frizz Quadrata TT (with increased font sizing to 14 pt) - **bug**.
- Reset the addon again, this time leaving the "Minimize completed quests" option unticked - **bug**.
- Reset again and left all settings at **DEFAULT**, font style, size, sorting, minimize completed quests unchecked, didn't even move tracker frame - **NO bug**.
- Changed all tracker fonts to PT Sans Narrow - **NO bug**.
- Increased tracker font sizes to 14 pt - **bug**
- Reverted font sizes to 10pt. Enabled Min Complete Quests option - **NO bug**
- Increased font sizes to 12 pt - **NO bug**
- Chaged sorting to By Proximity - **NO bug**

The easiest way for me to test from this point was by ctrl+clicking the header and dragging the tracker as far to the right of the screen. If the bug was still present the frame would grow each time, at 12 pt it did not.

So, for me at least, I can confirm @jak-lawrence  's experience: bug seems to present when the tracker font sizes (quest titles and objectives) are set above 12 pt.

**Comment by BreakBB** [comment] 2022-09-20 16:49
@Drac84 could you grab v7.1.3 and run your awesome tests again?

**Comment by Drac84** [comment] 2022-09-21 05:16
> @Drac84 could you grab v7.1.3 and run your awesome tests again?

@BreakBB No bug to report in 7.1.3. When tracker font sizes are set to 14 pt the frame bloat issue is no longer triggered when moving the frame to the edge of the screen or updating objectives. Increased all tracker font sizes to 18 pt just to be sure, no issues. 💯 

The resize handle also seems to be functioning normally again as a side-note, the bug tended to lock it so that you couldn't reduce the frame size, but it resizes freely now as well.

Thanks!

**Comment by BreakBB** [comment] 2022-09-21 07:46
Nice, thanks for testing it again and reporting back here as well @Drac84 I'll close this issue then. Feel free to open up a new one for everything else you may find 👍🏻

**Closed** 2022-09-21 07:47 UTC
Labels: Bug, Questie - Tracker
