### ISSUE TITLE
Map quest icons don't switch back to regular questie icons after unchecking "pfquest icons" option.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5041] opened 2023-07-17 12:40 UTC
When you check it, normal icons are changed with the pfquest icons, instantly.
If you uncheck it, they remain the same, and reopening the map doesn't change anyhing, only a /reload will make the icons show in line with the checked option.

https://github.com/Questie/Questie/assets/1155017/b775c8ac-107c-41e0-9b96-ec4023087482

8.8.2 wotlk

**Comment by Muehe** [comment] 2023-07-17 14:42
Just tested, this still works without problems on 8.8.1.

**Comment by Dyaxler** [comment] 2023-07-17 15:19
I just tested this on 8.8.2, still works without problems.

I did not change Muehe's toggle at all. When you toggle on and off it runs QuestieQuest:SmoothReset() which resets all the icon textures. However, I did notice that my recent changes does impact how icons are hidden in unexplored areas and the hide objectives for untracked quests.

Clearly, I need to rethink some of the logic behind that. @Cabro you can close this issue since it's not a bug. You can open another issue and reference `Hide icons of untracked quests` and `Hide unexplored area Icons`.

**Closed as completed** 2023-07-17 15:21 UTC
Labels: Bug

**Comment by Muehe** [comment] 2023-07-17 15:23
@Dyaxler You sure about that? I have the exact same problem on master, switch on and icons change, switch off and icons stay the same.

**Comment by tima9692** [comment] 2023-09-03 09:03
Is it possible to make small icons in pfquest as in quest, so that there are not dots but swords and bags?

**Comment by tima9692** [comment] 2023-09-03 09:04
Is it possible to make small icons in pfquest as in questie, so that there are not dots but swords and bags?
