### ISSUE TITLE
Dragonblight quest marker incorrect

### ISSUE THREAD

**Issue by RisaAudr** [Questie/Questie#4441] opened 2022-10-24 19:35 UTC
## Description
A dragonblight quest marker is incorrect. Quest is linked below. Marked is 52,66, and the correct location is (32.3, 71.9).  In the below screengrab, see coordinates. I (player) am directly on top of the target location, and "curser" is where questie currently has marked.

## Wowhead link
https://www.wowhead.com/wotlk/quest=12084/atop-the-woodlands

## Screenshots
![image](https://user-images.githubusercontent.com/116595021/197610175-526f106c-4ea5-42df-bb98-23ceab8dc30f.png)

## Questie & WoW version
- Version: 7.4.2
- Classic (WotLK) game version

Thanks!

**Comment by Yttrium-tYcLief** [comment] 2022-10-26 21:45
This behavior doesn't make any sense to me. This quest has been corrected - we've pointed at object `188474` and then explicitly overridden the spawns for `188474` to be *only* `{32.29,71.72}`. There isn't even an original spawn location in the 52,66 vicinity.

**Comment by Yttrium-tYcLief** [comment] 2022-10-26 21:51
Oh, my bad. The code makes sense because this was fixed in https://github.com/Questie/Questie/commit/80857008edeaabbaa386587b86a3dc5af7eefc24 4 days ago, but the fix hasn't made it to an official release soon. Closing since duplicate of #4375 (which will be closed when the next official release happens).

**Closed by Yttrium-tYcLief** 2022-10-26 21:51 UTC
Labels: Questie - Quest Issue, Data Correction
