### ISSUE TITLE
Questie: [ERROR] SortID: 0 was not found in the database.

### ISSUE THREAD

**Issue by Glaeks** [Questie/Questie#5322] opened 2023-12-19 18:51 UTC
## Bug description

The error pictured in the screenshot is being repeatedly spammed by questie upon logging in today. This is with the most recent update to questie as of 12/19/2023. This is on WoW: SoD. 
The error reads: "Questie: [ERROR] SortID: 0 was not found in the database. Please file a bug report at:" ....etc.

The quest in question seems to be "Meditation on the Light" for my dwarf priest. It reads as complete but I never handed it in.

## Screenshots

![image](https://github.com/Questie/Questie/assets/110417429/daabe8c3-3c36-4a35-a018-96366ad47c64)
![image](https://github.com/Questie/Questie/assets/110417429/5e05b3b1-eea8-47c5-aa5a-e3f817a8c96e)

## Questie & WoW version

Questie v9.2.8

**Comment by BreakBB** [comment] 2023-12-19 19:15
Duplicate of #5314 and already fixed. Thanks for the report, we'll ship the fix very soon!

**Closed by BreakBB** 2023-12-19 19:15 UTC
Labels: Bug
