### ISSUE TITLE
Massive 262 & 265 error spam when enable/disable options AND while in zones

### ISSUE THREAD

**Issue by gaymer77** [Questie/Questie#2924] opened 2021-06-08 05:15 UTC
I've read through the various reports on this site about the different errors and wanted to expand on the issues I'm seeing personally.  Whenever I pick up a quest item, open my quest log, change zones, loot mobs within dungeons (even when they are not linked to any type of quest), fly to one flight path to another within the same zone, and craft/enchant something I get at a minimum 3 error codes pop up.  Usually it says the error 265 but occasionally I'll get the 262.  When I am just out in the world I'm now getting the massive wall of text spam as noted in the first two pictures.  I should point out that although this happens while solo, it is more predominate while in a group.  It is literally every single time someone goes to loot something that it pops up with errors.  After reading through replies from people on these bug reports I saw that we should disable dungeon tracking as that is a cause of it due to mapping.  I did exactly that and this was what happened when I did it.  Massive spam of 262 & 265 error codes.  I am including the screenshots showing where I type "1" before I disabled and then "1 again after it was done with the spam.  This happened with dungeon, events, raid, AQ war effort, and in fact every single one of the "enable XX icons" in the check boxes.  I have tried disabling & enabling debug (under the advanced tab) but that just made everything spam my chat box constantly when it is disabled.  The massive spam only happens when I enable/disable options.  The minimum of 3 error codes happen as I stated above for every other time I do something.  I am using the current version of Questie which is 6.3.14-TBC.zip and have tried reverting back to version 3.13 but that does not clear anything up.  This only started happening a few days ago.  Prior to that there were no errors that happened.  Should also note that I am getting this spam of errors with ZERO other addons running.  This is strictly a Questie issue that is causing it.  Also adding this is happening in Outlands AND vanilla areas.  I have characters that have dungeon quests from vanilla that this is not affecting, a character with Hellfire dungeon quests that it is not happening with, but the character I have with Coilfang dungeon quests it is happening on.  I have also deleted my Questie folder, logged into the game with no Questie installed to fish out any shared settings, reinstalled Questie, and still have the massive error code spam.

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/Qx3WmJpn/Wo-WScrn-Shot-060721-215038.jpg' border='0' alt='Wo-WScrn-Shot-060721-215038'/></a>
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/pL0h2N3g/Wo-WScrn-Shot-060721-215025.jpg' border='0' alt='Wo-WScrn-Shot-060721-215025'/></a>

This is just sitting around Shat and the random spam I'm currently getting.  Timestamps are noted in the chat box.
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/hPWFHGsf/Wo-WScrn-Shot-060721-231202.jpg' border='0' alt='Wo-WScrn-Shot-060721-231202'/></a>

Below is one example of the "normal" error code spam that happens  when looting items (notice how 3 pop up).
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/cCG6GBkr/Wo-WScrn-Shot-060721-140236.jpg' border='0' alt='Wo-WScrn-Shot-060721-140236'/></a>

Honestly at this point I'd love to know just how to turn OFF the error code spam that happens in my chat screen.  The functionality of Questie isn't broken but the spam of error codes is making it almost to the point I want to stop using the addon.

**Comment by drejjmit** [comment] 2021-06-08 08:28
Duplicate of #2898

**Closed by drejjmit** 2021-06-08 08:28 UTC
Labels: Type - Defect
