### ISSUE TITLE
Error During Initialization

### ISSUE THREAD

**Issue by Athyyra** [Questie/Questie#6337] opened 2024-08-02 23:41 UTC
Error shows up when logging in. Here's my swatter log:

Date: 2024-08-02 19:37:26
ID: 1
Error occured in: Global
Count: 1
Message: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua line 15:
   attempt to index global 'QuestTimerFrame' (a nil value)
Debug:
   [string "@Interface/AddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua"]:15: in main chunk
Locals:
TrackerQuestTimers = <table> {
 private = <table> {
 }
}
QuestieTracker = <table> {
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:461
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2007
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:500
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1717
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:559
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1906
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:436
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2063
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:530
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2056
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1615
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2022
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1927
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:316
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:362
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1882
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:384
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1745
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:286
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1658
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1558
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:542
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:79
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:551
 private = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:512
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:269
}
LSM30 = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:294
 GetDefault = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:290
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:281
 GetGlobal = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:277
 List = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:267
 HashTable = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:263
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 IsValid = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibSharedMedia-
AddOns:
  Swatter, v4.4.6991 (SwimmingSeadragon)
  AtlasLootClassic, vv3.2.0
  AtlasLootClassicData, vv3.2.0
  AtlasLootClassicDungeonsAndRaids, vv3.2.0
  AucAdvanced, v4.4.6991 (SwimmingSeadragon)
  AucFilterBasic, v4.4.6991 (SwimmingSeadragon)
  AucStatHistogram, v4.4.6991 (SwimmingSeadragon)
  AucStatiLevel, v4.4.6991 (SwimmingSeadragon)
  AucStatPurchased, v4.4.6991 (SwimmingSeadragon)
  AucStatSimple, v4.4.6991 (SwimmingSeadragon)
  AucStatStdDev, v4.4.6991 (SwimmingSeadragon)
  AucUtilFixAH, v4.4.6991 (SwimmingSeadragon)
  BeanCounter, v4.4.6991 (SwimmingSeadragon)
  BetterBags, vv0.1.89
  BiSTooltipSoD, vv1.3 
  DBMCore, v11.0.2
  DBMStatusBarTimers, v11.0.2
  DBMVPVEM, veeae112
  DejaClassicStats, v11503r3
  ElvUI, vv13.72
  ElvUILibraries, vv13.72
  Enchantrix, v4.4.6991 (SwimmingSeadragon)
  EnchantrixBarker, v4.4.6991 (SwimmingSeadragon)
  FishingBuddy, v0.9.7
  GTFO, v5.10
  HighLevelAlert, v0.4.36
  IceHUD, vv1.15.3
  KillTrack, vv2.31.8
  Necrosis, v8.0.6
  NightmareIncursionHelper, v1.13
  NovaWorldBuffs, v2.88
  Questie, v10.3.9
  SlideBar, v4.4.6991 (SwimmingSeadragon)
  Stubby, v4.4.6991 (SwimmingSeadragon)
  BlizRuntimeLib v1.15.3.55917(US) <enUS>
  (ck=499)

**Comment by BreakBB** [comment] 2024-08-03 00:00
Duplicate of #6334

Blizzard just randomly removed an UI element Questie relied on. We are already working on a proper fix.

A workaround is here https://github.com/Questie/Questie/issues/6334#issuecomment-2266260275

**Closed by BreakBB** 2024-08-03 00:00 UTC
Labels: Bug
