### ISSUE TITLE
Still shows Objectives for Completed Quests 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4007] opened 2022-09-02 01:22 UTC
Wrath.

In a party, you still see the objectives for completed quests in tooltips.

We're both done with that quest, but it still shows in the tooltip.

![image](https://user-images.githubusercontent.com/55365231/188038923-cf4e0c99-4a1f-455b-a0c0-d8b0ed443d58.png)

**Comment by BreakBB** [comment] 2022-09-02 05:55
Duplicate of #3452

**Closed by BreakBB** 2022-09-02 05:55 UTC
Labels: Bug
