### ISSUE TITLE
Archmage Leryda appears as having available some Violet Eye quests when there are none.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3262] opened 2021-11-19 20:16 UTC
Similar to the Brood of Nozdormu rings quests, once you pick a path you have to reach exalted in order to get the quest that allows you to change the ring to a different style. However that is not the case, and it is a mess (from what i see).
What i see upon mouseover of the NPC:
https://imgur.com/9ghAnfN
What i see in map:
https://imgur.com/I2dwZ8w
What quest is actually available:
https://imgur.com/0rkQsMu

**Comment by Laumesis** [comment] 2021-11-19 20:23
Thanks reporting.

For those with write access:
Duplicate of #3100

**Closed** 2021-11-19 22:13 UTC
Labels: Bug
