### ISSUE TITLE
Questie Error for Bloodelf starter zone and Tauren TBC

### ISSUE THREAD

**Issue by IFrozenI** [Questie/Questie#2949] opened 2021-06-14 11:40 UTC
## BE and T bugg for questie?
Bloodelf starter zone displays Quest error "The quest 9325 is missing from questie's database". I also notist it only displayed 1 available quest on the world map which is "Kaltunk (4641)" please find screenshots of the issue below.

Also noticed similar errors with a tauren race at level 58 just entering outlands and no outland quest markers are showing at all. Quest errors are as followed "10450, 10121, 10086 missing from database"

![BE1](https://user-images.githubusercontent.com/85877981/121886644-8dab1300-cd0d-11eb-8d51-bf9bdbf31f24.png)
![BE2](https://user-images.githubusercontent.com/85877981/121886652-8f74d680-cd0d-11eb-9f49-4db4b55fdde5.png)
![BE3](https://user-images.githubusercontent.com/85877981/121886664-94398a80-cd0d-11eb-94f1-4f969e407c93.png)
![T1](https://user-images.githubusercontent.com/85877981/121886672-96034e00-cd0d-11eb-85bb-91d0b23151c6.png)
![T2](https://user-images.githubusercontent.com/85877981/121886675-97347b00-cd0d-11eb-8054-ca23dc71ee33.png)

Game version 2.5.1, questie version 6.3.15

Have tried multiple times to completely remove files and reinstall add on but still not working.

**Comment by drejjmit** [comment] 2021-06-14 11:43
Duplicate of #2938

**Closed by drejjmit** 2021-06-14 11:43 UTC
Labels: Questie - Quest Issue
