### ISSUE TITLE
Location of Har'koa NPC 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4636] opened 2023-01-30 05:54 UTC
Har'koa shows as having 2 locations.

Should only be the southern location.

https://www.wowhead.com/wotlk/npc=28401/harkoa

![image](https://user-images.githubusercontent.com/55365231/215398055-cf6de6b3-41ae-46e9-ad7d-520c27c1de80.png)

**Comment by BreakBB** [comment] 2023-01-30 06:19
Duplicate of #4557

**Closed by BreakBB** 2023-01-30 06:19 UTC
Labels: Bug
