### ISSUE TITLE
Im not sure entirely what happened honestly.

### ISSUE THREAD

**Issue by MeagerMuffin** [Questie/Questie#4118] opened 2022-09-13 23:07 UTC
## Bug description

Im not sure how it happ
![World of Warcraft 9_13_2022 5_55_06 PM](https://user-images.githubusercontent.com/113480540/190024493-d0d6a9ef-4944-4217-9128-81f444e033a9.png)
end honestly I just loaded up the game and it state ERROR Games quest cache log is not okay. This shouldn't happen. Questie may malfunction.

## Questie & WoW version

Currently using the WOTLK V7.1.1

**Comment by BreakBB** [comment] 2022-09-14 04:52
Duplicate of #4086

Nothing really to worry about @MeagerMuffin it's on our list to get fixed 👍🏻

**Closed by BreakBB** 2022-09-14 04:52 UTC
Labels: Bug
