### ISSUE TITLE
Windseer Grayhorn - Multiple quest markers, even though most aren't available yet

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4287] opened 2022-10-01 15:02 UTC
https://www.wowhead.com/wotlk/npc=27262/windseer-grayhorn

NPC currently shows 8 quests for me. None we're available when I was still 74. Now at 75 I could take 3 of them.

**Comment by Yttrium-tYcLief** [comment] 2022-10-01 17:43
Duplicate of #4248, and will be fixed with #4279

**Closed** 2022-10-01 23:08 UTC
Labels: Questie - Quest Issue, Data Correction
