### ISSUE TITLE
cachemiss error in chat

### ISSUE THREAD

**Issue by randyzie** [Questie/Questie#6706] opened 2024-11-27 22:52 UTC
### Description

Getting this line of text every time I check my mail, auction house, or interact with a vendor. Regular npcs don't seem to cause it that i've tested so far. Tested with only questie and still happens. No LUA errors.
`Nothing to update. cacheMiss, doRetryWithoutChanges false false`

### Questie version

v10.10.0-b1

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment] 2024-11-27 23:23
Duplicate of #6705 - Thanks for reporting this @randyzie and thanks for using a Questie beta version.

We'll ship a stable release very soon, which will contain the fix.

**Closed by BreakBB** 2024-11-27 23:23 UTC
Labels: Bug, Season of Discovery
