### ISSUE TITLE
Auto Turn In Issue

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4697] opened 2023-03-13 23:58 UTC
When you go to turn in a quest, and the NPC has another quest for you to pick up, but your quest log is full, it won't turn the quest in until you click manually.

It should always try and turn quests in first. Then pick them up after.

**Comment by BreakBB** [comment] 2023-03-24 19:01
Questie already tries to turn in quests before accepting new ones.

> it won't turn the quest in until you click manually.

This actually sounds like the Dragon Flight API issue, which was fixed in 31797bf1c1832a65cb2aa33782daa80c57e1a94f 🤔

**Comment by Cabro** [comment] 2023-03-24 19:04
I can confirm what Gogo said, Questie's had that behavior since I started using the addon.

**Comment by Gogo1951** [comment] 2023-03-26 08:05
Auto Complete is just broken. In whatever version is in Wrath.

Sometimes it works, but like 50%+ of the time it doesn't.

Should be easy to reproduce... it happens all the time. 

Hangs on Accept, hangs on Turn In, and it always tries to pick up quests before turning them in... I don't know how it used to work, but it worked better before. This has been noticeably different behavior for the last 2 months or so.

**Comment by BreakBB** [comment] 2023-04-24 20:54
Sorry for not checking twice on this @Gogo1951 and @Cabro I also just stumbled over the code which is "auto accept" and AFTERWARDS "auto turn in" 🙈 I'll see to switch that.

**Closed** 2023-04-24 21:12 UTC
Labels: Bug, Module - Auto
