### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Mabisi** [Questie/Questie#3144] opened 2021-08-30 13:33 UTC
The world map and name version that often accept tasks do not display task icons, and / RELOAD will appear again on the screen. Resetting the database can only last two tasks. The task was not accepted, but the task mark is displayed on the world map.

versin:V6.5.1 -TBC

**Comment by BreakBB** [comment] 2021-09-06 19:00
Hey @Mabisi I am not quite sure what exactly the issue is for you.

From what I understand you have problems with the quest objectives/icons are still showing for you even though you already completed the quest? And also sometimes no icons are showing after you accepted a quest?

**Comment by Mabisi** [comment] 2021-09-07 10:16
> Hey @Mabisi I am not quite sure what exactly the issue is for you.
> 
> From what I understand you have problems with the quest objectives/icons are still showing for you even though you already completed the quest? And also sometimes no icons are showing after you accepted a quest?

Yes!

**Comment by BreakBB** [comment] 2021-09-13 11:34
@Mabisi There is a nasty bug in Questie which causes exactly this behaviour. Most likely this will be fixed with #3111 - Closing this issuein favor of the Pull Request and the issues already linked in there.

**Closed by BreakBB** 2021-09-13 11:34 UTC
Labels: Bug
