### ISSUE TITLE
Valentine's Day Quests Still Show

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4687] opened 2023-03-11 19:09 UTC
![image](https://user-images.githubusercontent.com/55365231/224507191-ab61b189-7932-4f8e-93e8-9d61150fa6d4.png)

They are also not filtered correctly when you turn off "event quests."

**Comment by BreakBB** [comment] 2023-03-11 20:56
Duplicate of #4678

**Closed by BreakBB** 2023-03-11 20:56 UTC
Labels: Bug
