### ISSUE TITLE
Questie tracker repositions itself when achievements are tracked but no quests are tracked

### ISSUE THREAD

**Issue by Wheels387** [Questie/Questie#4478] opened 2022-11-03 18:01 UTC
## Bug description

When the Questie tracker is tracking an achievement and a quest, once the quest is no longer tracked (e.g. it was completed or manually untracked), the Questie tracker repositions itself much higher in the interface. Once a quest is tracked, the tracker returns back to its normal position.

## Screenshots

https://clipchamp.com/watch/fOXCj87mjM6

## Questie & WoW version

Version 7.4.4
WOTLK Classic

**Comment by Wheels387** [comment] 2022-11-04 13:14
I noticed something odd -- the resize handle changes when the last quest is untracked. Screenshot 1 shows normal behavior. Screenshot 2 occurs after the last quest is untracked. Notice that the resize handle in screenshot 1 is where it would be expected to be, but in screenshot 2 it is much further down despite the tracker not having anything in it.


![20221104-Questie-1](https://user-images.githubusercontent.com/87543798/199980682-4ac3c555-9536-4b7d-9fb2-7893fab880d3.png)
![20221104-Questie-2](https://user-images.githubusercontent.com/87543798/199980691-54b46c67-cc99-45e9-ad43-f8a3eaf0a3b2.png)

**Comment by BreakBB** [comment] 2022-11-08 06:50
Hey @Wheels387 that is a good report and the position issue you found might be very helpful! I hope to have some time soon to look into this and other issues.

**Comment by Muehe** [comment] 2023-01-22 03:57
@Wheels387 I seem to recall this bug and AFAIK it has been fixed in the meantime, and I can't reproduce with the steps given here. Thanks again for the report and please let us know if you notice anymore issues with the tracker.

**Closed by Muehe** 2023-01-22 03:57 UTC
Labels: Bug, Questie - Tracker
