### ISSUE TITLE
Weaponsmithing quests incorrectly shown as available to armorsmiths.

### ISSUE THREAD

**Issue by MisterTibbs** [Questie/Questie#2547] opened 2021-02-20 12:38 UTC
## Description
My character is an armorsmith and has completed all blacksmithing quests in the game except for these 4, I have checked the npcs in question and the quests are not available to me.

## Wowhead link
https://classic.wowhead.com/quest=8869/sweet-serenity
https://classic.wowhead.com/quest=5307/corruption
https://classic.wowhead.com/quest=5305/sweet-serenity
https://classic.wowhead.com/quest=5306/snakestone-of-the-shadow-huntress

## Screenshots
<img width="783" alt="questi1" src="https://user-images.githubusercontent.com/24671315/108595452-3c52ce80-7380-11eb-9d28-de85e878198b.png">
<img width="613" alt="questi2" src="https://user-images.githubusercontent.com/24671315/108595453-3e1c9200-7380-11eb-8861-b9b71edcdcfb.png">

## Questie version
v6.2.5

**Comment by Gogo1951** [comment] 2021-02-20 18:51
Dupe of #2004

**Closed by Gogo1951** 2021-02-20 18:51 UTC
Labels: Questie - Quest Issue
