### ISSUE TITLE
(OoD version) "The quest doesn't exist in QuestLogCache" - GetQuestObjectives, GetAllLeaderBoardDetails, MapIconTooltip

### ISSUE THREAD

**Issue by patinablot** [Questie/Questie#6435] opened 2024-09-28 02:21 UTC
## Bug description

Received error message which asked to be reported.

Corner minimap mouse-over of questie (?) icon for completed quest npc seemed to throw the error.
(Quest appears to be "Ride to Thunder Bluff".)

Message is attached as screenshot.

Message reads (preceding ellipses mine):
[string "@Interface/Addons/Questie/Modules/Quest/QuestLogCache.lua"]:337: in function 'GetQuestObjectives'

...Quest/QuestieQuest.lua:
... 1555: in function 'GetAllLeaderBoardDetails'
... 1529: in function 'Update'

...Tooltips/MapIconTooltip.lua"]:
... 139: in function 'handleMapIcon'
... 178: in function <...e/Addons/Questie/Modules/Tooltips/MapIconTooltip.lua:38>
[ERROR] Please report this error. GetQuestObjectives: The quest doesn't exist in QuestLogCache. 844

## Screenshots

![please-report](https://github.com/user-attachments/assets/6d8b3461-2c2a-43bc-aab3-a4b630cccdb6)

## Questie & WoW version

Looks like Questie is version 10.3.11.

I installed this folder manually.

This is on classic SoD. (Version 1.15.4.56760)

**Comment by BreakBB** [comment] 2024-09-30 09:34
Hey @patinablot did this error just popped up that one time? It seems like Questie was too slow to handle the game events correctly 🤔

**Comment by BreakBB** [comment] 2024-12-18 10:29
Closing this as this is a duplicate of #6695

The addon "Minimap Alert" somehow hooks the Questie icons and therefore calls tooltip related functions too early/late.

**Closed by BreakBB** 2024-12-18 10:29 UTC
Labels: Bug
