### ISSUE TITLE
Quest tracker keeps opening.

### ISSUE THREAD

**Issue by Cojaxod** [Questie/Questie#3072] opened 2021-07-27 13:30 UTC
When ever I enter a new zone the quest tracker opens up, or when I exit a battle ground. It wasn't all ways like this and would remain minimized. Is there anyway to keep it minimized?

**Comment by Laumesis** [comment] 2021-07-27 18:16
Duplicate of issue #3046 , which also tells workaround until fix

**Closed** 2021-07-27 20:49 UTC
Labels: Type - Miscellaneous Task
