### ISSUE TITLE
Questie Error during initialization

### ISSUE THREAD

**Issue by Branibor92** [Questie/Questie#6338] opened 2024-08-02 23:46 UTC
Hello, i have problem with Questie for Classic Era, im getting error like shown on a picture...
I tried reinstalling, downloading manually, downloading older versions, still got same message, can you help me resolve this issue?
![scsc](https://github.com/user-attachments/assets/84cf4d1a-e650-4469-9dae-df3d59f1b427)

**Comment by Ganesh1337** [comment] 2024-08-02 23:50
i have the same problem, wanted to post it but maybe the account is too new.

[01:22] Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Modules/QuestieInit.lua:281: attempt to call method 'Initialize' (a nil value)

**Comment by Squeaksqt** [comment] 2024-08-02 23:52
I posted it earlieir as well.

**Comment by Squeaksqt** [comment] 2024-08-02 23:57
![image](https://github.com/user-attachments/assets/0b023c3e-4514-4629-ac9a-3973bb0aef04)

got this to work!

**Comment by BreakBB** [comment] 2024-08-02 23:59
Duplicate of #6334

Blizzard just randomly removed an UI element Questie relied on. We are already working on a proper fix.

A workaround is here https://github.com/Questie/Questie/issues/6334#issuecomment-2266260275

**Closed by BreakBB** 2024-08-02 23:59 UTC
Labels: Bug

**Comment by Branibor92** [comment] 2024-08-03 01:06
This worked for me. Thank you very much.
