### ISSUE TITLE
Some Error often

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#3036] opened 2021-07-19 14:05 UTC
2x Questie\Modules\Libs\QuestieLib.lua:257: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Questie\Modules\Libs\QuestieLib.lua"]:257: in function `GetTbcLevel'
[string "@Questie\Modules\Tooltips\ChatFilter.lua"]:35: in function `filterFunc'
[string "@Prat-3.0-3.9.1\services\chatsections.lua"]:49: in function <Prat-3.0\services\chatsections.lua:41>
[string "@Prat-3.0-3.9.1\services\chatsections.lua"]:340: in function `SplitChatMessage'
[string "@Prat-3.0-3.9.1\addon\addon.lua"]:639: in function <Prat-3.0\addon\addon.lua:613>
[string "=(tail call)"]: ?
[string "@FrameXML\ChatFrame.lua"]:2930: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

[Prat-TBC](https://www.curseforge.com/wow/addons/prat-tbc)
I asked about error with Prat-TBC Author
This is what he(she) said

In reply to 아련별:

 Are you sure this is error from prat? looks like error from questie.

**Comment by drejjmit** [comment] 2021-07-22 00:15
I've been using Prat with Questie since TBC release and never seen this error.
I use this version tho: <https://github.com/Road-block/prat-3-0/releases/tag/3.9.1-6>
Can you see if that one works for you?

**Comment by SunnyJang38** [comment] 2021-07-22 00:56
> I've been using Prat with Questie since TBC release and never seen this error.
> I use this version tho: https://github.com/Road-block/prat-3-0/releases/tag/3.9.1-6
> Can you see if that one works for you?

i used that version but it's same error

**Comment by drejjmit** [comment] 2021-07-22 10:18
How can we reproduce it?

**Comment by Muehe** [comment] 2021-07-23 20:05
@SunnyJang38 There are some file references in the error log that don't exist in Questie anymore, so there probably is something broken on the file-system level.

Please delete the Questie folder from `Interface/AddOns` dir (if there is more than one that's probably the reason for the bug) and replace it with [the current release](https://github.com/Questie/Questie/releases/latest) (6.5.0). Make sure to restart the WoW client!

If that doesn't help, try closing WoW, renaming the `WTF` dir to something else. This will remove **all** settings (even resolution and such) and addon data from WoW, so don't delete if you don't want to reconfigure everything manually. If that doesn't help as well you can delete the new `WTF` and rename the old one back to restore your settings.

**Comment by Laumesis** [comment] 2021-09-06 23:37
Dublicate of #3146
Refering this way to newer issue as it has up to date error instead one from old Questie version.

**Closed** 2021-09-10 05:27 UTC
Labels: Bug
