### ISSUE TITLE
Bailor's Ore Shipment wrong drop location

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2561] opened 2021-03-02 10:04 UTC
## Description
Paladin class quest "Bailor's Ore Shipment" is shown incorrectly as drops from mobs

## Wowhead link
https://classic.wowhead.com/quest=1655/bailors-ore-shipment

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/109632105-f992b280-7b46-11eb-9465-ebd0597811da.png)

## Questie version
v6.2.5

**Comment by Gogo1951** [comment] 2021-03-02 20:06
Dupe of https://github.com/Questie/Questie/issues/2488

**Closed** 2021-03-05 10:47 UTC
Labels: Questie - Quest Issue, Type - Defect
