### ISSUE TITLE
[Cata] Shrouded in Nightmare (8446) no longer obtainable

### ISSUE THREAD

**Issue by entroscopy** [Questie/Questie#6366] opened 2024-08-07 18:03 UTC
## Description
The quest Shrouded in Nightmare (8446) is not obtainable as the dragons of nightmare have been removed with Cataclysm.

## Wowhead link
https://www.wowhead.com/cata/quest=8446/shrouded-in-nightmare

## Questie & WoW version
WoW 4.4.0.56014
Questie 10.3.11

**Comment by coldpasta123** [comment] 2024-08-07 21:21
Duplicate of #6231 and due to be fixed with https://github.com/Questie/Questie/pull/6359/commits/ebf9823e09ad2812ca87d88ccfb8d9b2ed6777bb

**Closed** 2024-08-07 22:27 UTC
Labels: Data Correction
