### ISSUE TITLE
Grunt work quest error

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4030] opened 2022-09-04 02:09 UTC
## Bug description

Quest A Grunt's Work... (10702) not showing locations of mobs right now and if you kill any mob addon will give many errors

## Questie & WoW version
7.0.1, Wrath

**Comment by BreakBB** [comment] 2022-09-04 07:20
Duplicate of #3998 we are on it, thanks for the report @Firehex12 👍🏻

**Closed by BreakBB** 2022-09-04 07:20 UTC
Labels: Bug
