### ISSUE TITLE
Questie broken

### ISSUE THREAD

**Issue by Theepiclord911** [Questie/Questie#6336] opened 2024-08-02 23:39 UTC
I play SOD and updated my addons, accidentally updated pirated RXP so it bugged had to reinstall it and decided to also delete RXP SavedVariables. I join back and I get "Error during initialization! Interface/Addons/Questie/Modules/QuestieInit.lua:281: attempt to call method 'Initialize' (a nil value)". I've cleared SavedVariables and reinstalled Questie (10.3.9) and nothing has worked. I think RXP interferes with Questie somehow, though it has never done it before. So I removed RXP and it's SavedVariables and reinstalled Questie but it still doesn't work. Also disabled all addons and reinstalled Questie, still doesn't work. I can't interact with the minimap Questie button and can't see any icons on the map. But I can go to "Interface > Addons > Questie" and check the options from there. Error popup message below

Date: 2024-08-03 01:32:07
ID: 1
Error occured in: Global
Count: 1
Message: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua line 15:
   attempt to index global 'QuestTimerFrame' (a nil value)
Debug:
   [string "@Interface/AddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua"]:15: in main chunk
Locals:
TrackerQuestTimers = <table> {
 private = <table> {
 }
}
QuestieTracker = <table> {
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:461
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2007
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:500
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1717
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:559
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1906
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:436
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2063
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:530
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2056
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1615
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2022
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1927
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:316
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:362
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1882
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:384
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1745
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:286
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1658
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1558
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:542
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:79
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:551
 private = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:512
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:269

**Comment by BreakBB** [comment] 2024-08-02 23:59
Duplicate of #6334

Blizzard just randomly removed an UI element Questie relied on. We are already working on a proper fix.

A workaround is here https://github.com/Questie/Questie/issues/6334#issuecomment-2266260275

**Closed by BreakBB** 2024-08-02 23:59 UTC
Labels: Bug
