### ISSUE TITLE
Issue showing class trainers

### ISSUE THREAD

**Issue by Aranoa** [Questie/Questie#2597] opened 2021-03-22 20:48 UTC
I deleted a character who was a warrior and then made a new character using the same name. When I started playing with the new character (a druid) and added Class Trainers to my list of what I wanted to see on my map instead of showing druid class trainers the addon continued to show warrior class trainers only. I've reloaded questie, reinstalled it and the problem still remains. Is there a way to remedy this?
I am using Questie v6.2.5

**Comment by BreakBB** [comment] 2021-03-23 06:12
Hmm... Sounds like we are not resetting something correctly. We will look into this. The same name could be a problem.

For now you should be able to reset Questie using [#2 of the FAQ](https://github.com/Questie/Questie/wiki/FAQ#2-questie-still-doesnt-show-anything). If you do not care about your Journey data though.

**Comment by Aranoa** [comment] 2021-03-23 10:20
This worked fine! I assume the name will be the problem because I've had similar experiences with Recount where when I first log on to the new character with the same name and don't edit the addon at all then the automatic colour of the dps bar is that of the previous class rather than the new one. It's only a tiny problem and I doubt other people don't delete and recreate characters at the rate I do haha.
Thanks very much for the help though!

**Comment by BreakBB** [comment] 2021-03-23 15:47
Glad you were able to fix the issue. I will keep this open so we can investigate the cause once we have time.

**Comment by BreakBB** [comment] 2023-06-10 12:03
Closing this in favor of #3420

**Closed by BreakBB** 2023-06-10 12:03 UTC
Labels: Bug
