### ISSUE TITLE
Extraobjective icons on map for quests that are complete are re-drawn after a /reload

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5001] opened 2023-06-27 12:07 UTC
![image](https://github.com/Questie/Questie/assets/1155017/29223399-cc9f-47a0-8c78-4acf74de538e)

8.7.2

**Comment by Dyaxler** [comment] 2023-06-27 14:52
@Cabro 

Is this a bug caused by something else I fixed or is this something that wasn't fixed in @BreakBB PR?
https://github.com/Questie/Questie/pull/4962

**Comment by BreakBB** [comment] 2023-06-27 15:03
My PR didn’t cover this as it seems. It only hides the marked when completing the quest but they re appear on reload @Dyaxler

**Comment by Cabro** [comment] 2023-06-27 15:04
This was fixed in one of your earlier PRs, if you remember when you did it and we were testing with extraobjective with text "test". It came back it seems.

**Comment by Dyaxler** [comment] 2023-06-27 15:43
I think I also remember mentioning that this could happen because the flag we set upon completion... I didn't want to create another GLOBAL setting which would be required in order to survive a reloadUI. This scenario/text case shouldn't come up very often.

**Comment by Cabro** [comment] 2023-06-27 15:44
Now you're just ping pong-ing this :D

**Comment by Dyaxler** [comment] 2023-06-27 15:45
Not trying to lay blame on me or him. :D I just don't want to come in and fix this if it's something @BreakBB was going to already address. I'd be happy to assign this to me and take care of it.

**Comment by Cabro** [comment] 2023-06-27 16:43
Turns out they are not removed at all. /reload doesn't even matter
Any chance the server swap layers counts as a new enter_world event?

**Comment by Cabro** [comment] 2023-06-27 20:29
This is becoming visible each time you log a different char, so the chances for this bug to happen are pretty high, i'd say :(

**Comment by BreakBB** [comment] 2023-06-28 05:52
I am not sure when exactly I will be able to tackle this. If you have a good idea go ahead @Dyaxler - This shouldn't require a global because even on reload we know if an objective is complete or not.

**Comment by Nightmaxman** [comment] 2023-06-28 10:10
Can we get back to this (version 8.7.0)?
![qw02](https://github.com/Questie/Questie/assets/138003982/0943f5be-22a6-4af6-93f7-4dd1e972c058)

Because now its look like this (version 8.7.2)
![qw01](https://github.com/Questie/Questie/assets/138003982/dcc3f48c-6f01-4be1-b213-2c42115c3a8b)

Thanks in advance!

**Comment by BreakBB** [comment] 2023-06-28 10:17
Hey @Nightmaxman completely different issue. We are working on your issue as well though.

**Comment by Nightmaxman** [comment] 2023-06-28 10:58
Ok, thanks !

**Comment by Dyaxler** [comment] 2023-07-01 20:14
@Cabro So I've circled around back to this issue...

Is it just the tooltips for NPC's that is showing this "extraObjective"? RE: the "Mount up" text...

What about the other icons? Do the spawn/monster icons still exist or did they disappear when you completed the quest?

**Comment by Cabro** [comment] 2023-07-01 20:15
The regular objective map markers are not re-drawn. It's ONLY the extraobjective ones

**Comment by MyTechnoHunter** [comment] 2023-07-01 20:19
for clarity, are we talking icons on map or tooltips? the topic implies icons.. dyaxlers question says tooltip.. which are we playing with here?

**Comment by Cabro** [comment] 2023-07-01 20:20
The icons on map/minimap. I know that the mouseover on creature/object tooltips will be handled at a later point.

**Comment by Dyaxler** [comment] 2023-07-01 20:37
Does the "Finisher" icon appear correctly after you login/reloadUI?

**Comment by Dyaxler** [comment] 2023-07-02 00:26
Fixed in PR: https://github.com/Questie/Questie/pull/5013

**Closed** 2023-07-16 14:40 UTC
Labels: Bug, Module - Map / Minimap, Module - Tooltips, Module - Quest
