### ISSUE TITLE
Map button bug in TBC

### ISSUE THREAD

**Issue by weichangxing** [Questie/Questie#3239] opened 2021-11-09 13:16 UTC
When i enable or only enable Questie, i cant see the map original button, like that.
![image](https://user-images.githubusercontent.com/41605627/140930006-ce903fba-5cc6-4790-abda-db8338217e84.png)
![image](https://user-images.githubusercontent.com/41605627/140930107-92bdbad9-465c-42cc-a934-e8fba3b65807.png)

This bug still in 6.6.* version,how can i do?

This is disble all addons screenshot
![image](https://user-images.githubusercontent.com/41605627/140930704-5115a961-1980-4234-bfdf-04732972b04e.png)

TBC version: 2.5.2.40892
Questie version: 6.7.0, 6.6.*

**Comment by Laumesis** [comment] 2021-11-12 14:58
See for example #3221

**Comment by BreakBB** [comment] 2021-11-16 22:46
Closing this for now, since this is not a bug but a workaround we added for taint issues, which breaks the whole UI thanks for Blizzard. When Blizzard fixes these issues, we will show the buttons again.

**Closed by BreakBB** 2021-11-16 22:46 UTC
