### ISSUE TITLE
About Completed Quest Show on the map again

### ISSUE THREAD

**Issue by zhangxiuwei911** [Questie/Questie#4496] opened 2022-11-05 13:30 UTC
When I Completed a Quest,I logout,then I login,the Completed Quest Show on the map again,why is that happened？
I delete the Cache and WTF,it still go the same,please help me or show me how to modify the addon file by myself,THX a lot!

**Comment by zhangxiuwei911** [comment] 2022-11-05 23:21
I mean the quest"!" has being shown on the map and the minimap again even I completed,after I logout and login,I recommend to add Local cache that Avoid this situation,not scan the severs,in your next update.Just a suggestion :)
Your work is remarkable by the way.

**Comment by Yttrium-tYcLief** [comment] 2022-11-06 07:35
There is a local cache.

Which exact quest(s) is this happening for? What version of Questie are you running?

**Comment by zhangxiuwei911** [comment] 2022-11-06 13:17
All the Completed Quests and the newest version.I don't know why,it seams have some issues in check the severs

**Comment by BreakBB** [comment] 2022-11-09 06:28
Hey @zhangxiuwei911 could you do the following for us?

1. Activate quest IDs (͘˙/questie` -> Advanced -> Show Quest IDs)
2. Pick one of the quests that is still showing while it shouldn't
3. Run the following command in the ingame chat with the quest ID of the quest you picked: `/dump C_QuestLog.IsQuestFlaggedCompleted(<yourQuestID>)`
4. Take a screenshot after you run the command and while you hover over the quest you picked
5. Post that screenshot here (you can just copy paste it directly)

**Comment by Muehe** [comment] 2023-01-22 03:52
@zhangxiuwei911 Hey, I'm closing this issue because we cannot reproduce the problem and you didn't provide any more info, so there is nothing we can do for now.

If you still have this problem please let us know in this issue or a new one, thanks.

**Closed by Muehe** 2023-01-22 03:52 UTC
Labels: Question
