### ISSUE TITLE
Blind Cazul Quest

### ISSUE THREAD

**Issue by Necril** [Questie/Questie#4436] opened 2022-10-23 11:38 UTC
## Description
There's a marker on the map in Orgrimmar but the quest doesn't exist. The marker levels up with the character.

## Wowhead link
https://www.wowhead.com/classic/quest=1508/blind-cazul#comments

## Questie & WoW version
Questie: 7.4.2
WotLK Classic: 3.4.0.46248

**Comment by Yttrium-tYcLief** [comment] 2022-10-26 21:40
Can you share a little more info about your situation?

What are your character level, class, race?

Using Questie Journey (`/questie journey` > Advanced Search), have you completed quests 1472 or 1507?

**Comment by Necril** [comment] 2022-10-27 10:43
I kept seeing the Q from around lvl 50 and way past 60. I hid it because I kept checking if it's actually there yet and it never was.

I get no matches for the Qs you listed.

**Comment by BreakBB** [comment] 2022-10-27 11:30
Hey @Necril an alternative to get the information we need is to run the following commands in game chat and report the output:

`/dump C_QuestLog.IsQuestFlaggedCompleted(1472)`
`/dump C_QuestLog.IsQuestFlaggedCompleted(1507)`

**Comment by Necril** [comment] 2022-10-27 14:08
Oh, I'm sorry. I got it now:
1472: Complete
1507: Not complete

The dump commands worked, however searching in Advanced Search with "Search by ID" by writing or pasting the IDs replaces the ID with random items' names and I can't get a result.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 14:10
Just to clarify - what race is your character?

I'm trying to gather as much info about your character's situation so I can figure out why Questie thinks you're eligible for this quest and is displaying it for you, when you're actually not eligible at all.

**Comment by Necril** [comment] 2022-10-27 14:18
Undead warlock

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 19:46
Okay, I think I see what's going on here. So this is for the Succubus quest chain. There's a breadcrumb called "Devourer of Souls" (`1507` in Orgrimmar, `1472` in Undercity) which leads you to start the chain. For Orcs, `1507` is supposed to lead to `1508` "Blind Cazul", and for Undead, 1472 is supposed to lead to `1476` "Hearts of the Pure". However, for some reason, not only are these quests not race-locked, but the `1507` breadcrumb unlocks *both* `1508` *and* `1476`, and the `1472` breadcrumb unlocks *both* `1476` *and* `1508`. So, in essence, if you do either breadcrumb for either race, Questie thinks *both* race quest chains are unlocked.

Now the interesting note here is that after testing on the SoM PTR, it seems that *both* races are, in fact, eligible for *both* breadcrumbs and chains. However, once you complete the *real* first step of either chain (`1476` "Hearts of the Pure" or `1508` "Blind Cazul"), you are locked into doing *that* chain. The logic Questie is missing is that last bit - locking you out of the opposite chain.

I'll continue to figure out the nuances at play here, but will issue a fix soon.

**Comment by Necril** [comment] 2022-10-27 19:49
I noticed the locking part but with another quest. When I could get the Succubus I saw that the quest giver had 2 quests, but when I accepted the Succubus quest, the other one vanished. I abandoned it, took the other (Incubus, yes they added them to WotLK), BUT the Succubus quest didn't vanish. I did both and got duplicate rewards, plus the actual summoning spells.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 19:53
That part is intentional, and it's even in Classic Era too actually. The Incubus variant on Undead side is called Hearts of the Lovers (instead of Hearts of the Pure for Succubus). We have some incorrect info regarding those quests, I'll see about cleaning that up too.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 21:00
Okay so:

You can actually do *all* of the quest chains, even if you already have the Succubus. The breadcrumbs *are* required to begin each chain, but only begin their corresponding chain. The *only* exclusive quest is "The Binding", which is the final one where you summon the Succubus - if you've already completed one of the "The Binding" quests, you cannot do the others. It's up to you which one you choose to do.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 21:29
Okay I've got some fixes regarding this quest chain, but... I've gotta be honest, none of these fixes have anything to do with `1508` and I have absolutely zero insight as to why that quest is showing for you. No matter what, all three of our databases clearly declare that `1508` *requires* `1507`, and you've stated pretty clearly that you haven't done `1507`.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 21:36
As a sanity check (because I have been going insane for the last 3 hours trying to figure this out), can you do me a favor:

1. Go to `/questie` > Advanced, and enable "Show Quest IDs"
2. Go to `/questie journey` > Advanced Search > Search By Name, search for "Blind Cazul", expand the window fully, and take a screenshot like so:
![image](https://user-images.githubusercontent.com/1037011/198402661-1f231259-3e04-4e3f-a29c-13b71a8af6bf.png)

3. Do the same for "Devourer of Souls":
![image](https://user-images.githubusercontent.com/1037011/198402793-f04733b0-0647-42bd-80ad-77a4c0289a08.png)

4. And "Hearts of the":
![image](https://user-images.githubusercontent.com/1037011/198402917-2cb9d71a-86ae-466a-bd01-4a5c99f9d5d1.png)

5. And "The Binding":
![image](https://user-images.githubusercontent.com/1037011/198403012-59b48607-ab6f-4bd7-8a55-a287dfc74c2f.png)

**Comment by Necril** [comment] 2022-10-28 10:13
![WoWScrnShot_102822_130931](https://user-images.githubusercontent.com/56406246/198563389-b90159a3-ac1a-453e-894f-50536e6f04f2.jpg)
![WoWScrnShot_102822_130953](https://user-images.githubusercontent.com/56406246/198563397-29232149-bddc-4178-86d3-b23133468099.jpg)
![WoWScrnShot_102822_131012](https://user-images.githubusercontent.com/56406246/198563399-1a63c33a-c459-4b4a-9fc5-b933412deb32.jpg)
![WoWScrnShot_102822_131022](https://user-images.githubusercontent.com/56406246/198563402-e6b31a38-d142-4d1f-9c06-5befc6ed14e5.jpg)

**Comment by Yttrium-tYcLief** [comment] 2022-10-28 17:48
And just to confirm - if you unhide it, and then do a recompile (`/questie` > Advanced > Recompile Database), after Questie fully loads it still shows up on the map, despite all of this?

If so, this isn't a data error, this must be something deeper because this quest *clearly* has a pre-req (`1507`) that you have not completed, so under no circumstance should it appear.

**Comment by Necril** [comment] 2022-10-30 08:29
Yep, it reappeared. Now I see it as lvl 78.

**Comment by Yttrium-tYcLief** [comment] 2022-10-30 23:17
The level scaling is correct, that was something that Blizzard implemented in TBC for a few quests. Obviously it shouldn't be showing up though. I'm going to go ahead and change the labels on this issue - unless there's something obvious I'm missing, this isn't a data issue. Gunna pull @BreakBB in on this.

**Comment by BreakBB** [comment] 2023-04-27 18:07
Hey @Necril sorry for not shiming in earlier... Are you still playing the game and is this still an issue you can reproduce?

I modified my game to make it think I completed all the quests you showed from your Journey and also I did not complete the ones you didn't. Though I can't get "Blind Cazul" to show up 🙈

**Comment by BreakBB** [comment] 2023-09-15 13:33
Closing this issue, due to lack of information.

**Closed by BreakBB** 2023-09-15 13:33 UTC
Labels: Bug, Module - Map / Minimap
