### ISSUE TITLE
Error - Error during initialization!

### ISSUE THREAD

**Issue by concursuswow** [Questie/Questie#6345] opened 2024-08-03 01:02 UTC
## Bug description
Upon logging into wow classic era today, my Questie addon is entirely non-functional. I can't access the mini-map button with any mouse click. I can not open settings with /questie. The addon is not tracking quests, or objectives on the map or minimap. The addon is entirely broken, and it is returning an error

ERROR TEXT:
Message: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua:15: attempt to index global 'QuestTimerFrame' (a nil value)
Time: Fri Aug  2 17:52:30 2024
Count: 1
Stack: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua:15: attempt to index global 'QuestTimerFrame' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua"]:15: in main chunk

Locals: TrackerQuestTimers = <table> {
 private = <table> {
 }
}
QuestieTracker = <table> {
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:461
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2007
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:500
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1717
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:559
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1906
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:436
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2063
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:530
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2056
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1615
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2022
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1927
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:316
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:362
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1882
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:384
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1745
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:286
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1658
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1558
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:542
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:79
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:551
 private = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:512
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:269
}
LSM30 = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @Interface/AddOns/Questie/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:293
 GetDefault = <function> defined @Interface/AddOns/Questie/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:289
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Interface/AddOns/ClassicHealPrediction/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @Interface/AddOns/Questie/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:280
 GetGlobal = <function> defined @Interface/AddOns/Questie/Libs/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:276
 List = <funct

## Screenshots
![WoWScrnShot_080224_175837](https://github.com/user-attachments/assets/4bb9f6eb-2191-4842-b062-9d6778d71afc)
![WoWScrnShot_080224_175844](https://github.com/user-attachments/assets/22e8a54a-62be-4749-82fc-415719813bba)
![WoWScrnShot_080224_175856](https://github.com/user-attachments/assets/79e42a0d-fb56-4e99-87dc-bfb454f21ac6)
![WoWScrnShot_080224_175857](https://github.com/user-attachments/assets/264c8f62-b5b7-4c56-a942-4e9a140ff312)

## Questie & WoW version
Questie Version:  10.3.9
WoW Classic Version:  1.15.3

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
Classic Era, on all servers I have characters on.

**Comment by BreakBB** [comment] 2024-08-03 01:05
Duplicate of #6334

A fix is already released and available on all platforms.

**Closed** 2024-08-03 01:05 UTC
Labels: Bug
