### ISSUE TITLE
Map bug when accepting new quests

### ISSUE THREAD

**Issue by Bacrdimike** [Questie/Questie#4426] opened 2022-10-19 01:55 UTC
## Bug description

When I accept a new quest the bug happens. I am leveling currently in Northrend.

## Screenshots

5x Questie\Modules\Map\QuestieMap.lua:839: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@Questie\Modules\Map\QuestieMap.lua"]:839: in function `GetNearestSpawn'
[string "@Questie\Modules\Map\QuestieMap.lua"]:927: in function `GetNearestQuestSpawn'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1385: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:1370>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:658: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:568>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:732: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1339: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:25: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:17>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by orionshock** [comment] 2022-10-23 16:33
```1x Questie\Modules\Map\QuestieMap.lua:844: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@Questie\Modules\Map\QuestieMap.lua"]:844: in function `GetNearestSpawn'
[string "@Questie\Modules\Map\QuestieMap.lua"]:932: in function `GetNearestQuestSpawn'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1385: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:1370>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:658: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:568>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:732: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1339: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:25: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:17>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
```

Is what im getting - similar i think

**Comment by BreakBB** [comment] 2022-11-09 06:35
Hey @orionshock @Bacrdimike sorry for the very late response on this. We thought this to already be fixed in one of the last updates, but that is actually not true.

Does this error happen every time you accept a quest? I am quite sure it is linked to the sorting of the Tracker you are using. Sorting "By Zone" instead of "Proximity" should keep this issue away for now.

**Comment by Muehe** [comment] 2023-01-22 04:19
@BreakBB I can't reproduce this, even with tracker sorted by proximity. I think we can close this as it has been fixed since, but not sure if you had reproduction back in November so leaving this one to you.

**Comment by BreakBB** [comment] 2023-01-22 10:02
@Muehe I also can't reproduce this anymore and sorting by proximity seems to work just fine. Closing this

**Closed by BreakBB** 2023-01-22 10:02 UTC
Labels: Bug, Questie - Map / Minimap, Needs testing/reproduction
