### ISSUE TITLE
Game Freeze after update 8.0.1

### ISSUE THREAD

**Issue by Tregoen** [Questie/Questie#4803] opened 2023-04-25 02:43 UTC
WOWLTKING

Originally using Questie v8.0.,0 - was updated to v8.0.1 and immediately noticed an issue when loading in game map ---  game would pause.. each time for about 5 seconds.. the eventually game froze altogether. Disabled Questie and issue no longer occurred. Attempt full reboot with V8.0.1 enabled - same issue. Down gr4aded to v8.0.0 ... issue no longer occurred..... however the following error appeared for a quest I do not have,,

![image](https://user-images.githubusercontent.com/131732280/234161309-05e261f3-2281-48c0-b3e2-6f3ea6483d70.png)

**Comment by BreakBB** [comment] 2023-04-25 05:26
It seems you have "Debug" enabled @Tregoen which is not recommended for regular Questie users. That's the reason the warning shows up, nothing for you to worry about.

Did you also try to disable all other addons to see if the game still freezes?

**Comment by Dyaxler** [comment] 2023-04-25 14:44
Also try this... 

If you can disable debug in Questie Config --> Advanced before your game freezes.
Also attempt to disable the Tracker by going to the Tracker tab and hit the button. Your UI will reload.

This will disable the tracker and load everything else. It'll tell me if the issue is with the Tracker code specifically.

**Comment by Tregoen** [comment] 2023-04-29 01:31
Hi ���. I rolled back to v8.0.0 and after 3 days of no issues the game freezing when switching to map reoccurred and I got the attached error. I did a game restart and it seemed to clear up.

Will send more if you want if anything occurs again.

 �

The following are my settings.


	
		
 �




 �


	
		

Date: 2023-04-29 12:53:11
ID: 1
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_ItemButton12:SetAttribute()) during combat lockdown.
Debug:
   [string "=[C]"]: SetAttribute()
   [string ***@***.***/AddOns/Questie/Modules/Tracker/TrackerLinePool.lua"]:450: SetItem()
   [string ***@***.***/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:609: Update()
   [string ***@***.***/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:185:
      ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:184
Locals:
None
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.8.5
  Atlas, vv1.52.07
  AtlasBattlegrounds, vv1.52.02
  AtlasBurningCrusade, vv1.52.02
  AtlasClassicWoW, vv1.52.04
  AtlasDungeonLocs, vv1.52.02
  AtlasLegion, vv1.47.01
  AtlasWrathoftheLichKing, vv1.52.02
  AtlasMajorCitiesEnhanced, vv1.16
  Buffet, v3.4.0.96
  CTBarMod, v10.0.7.2
  CTBottomBar, v10.0.5.2
  CTBuffMod, v10.0.0.4
  CTCore, v10.0.2.5
  CTLibrary, v10.0.2.5
  CTMailMod, v10.0.7.1
  CTMapMod, v10.0.5.2
  CTPartyBuffs, v10.0.2.3
  CTUnitFrames, v10.0.7.1
  CTViewport, v9.2.0.3
  Decursive, v2.7.9.1
  LibStub, v
  LibTouristClassic10, v
  Questie, v8.0.0
  Recount, vv3.4.1b
  RepairBroker, v10.0.7
  Scrap, v10.0.10
  SheepMonitor, v1.24
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.4.0
  ZoneInfoClassic, v1.0
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=357)

**Comment by Dyaxler** [comment] 2023-04-29 04:44
This relates to the Quest Item Buttons. There is a fix for that in the current branch. Not released yet. Soon.

**Comment by BreakBB** [comment] 2023-04-29 08:54
Fixed in https://github.com/Questie/Questie/commit/08b40feade5537cf4c1dcfb6eaeb593953f551a5

**Closed** 2023-04-29 08:54 UTC
Labels: Bug, Module - Tracker

**Comment by Tregoen** [comment] 2023-04-30 01:48
Not sure if you want this one or not … so I just decided to send it

 �

 �

 �

Dave Parkin

E:  ***@***.***> ***@***.***

M: +64274550671

 �

 �

 �

 �

 �

**Comment by MyTechnoHunter** [comment] 2023-04-30 01:49
details please, is this a new error relating to the game freezing using a button? or something else dealing with the worldmap?

**Comment by Tregoen** [comment] 2023-04-30 02:28
Its kinda weird….. selected MAP and the game froze up  for about I minute… and even hitting exit did nothing… then suddenly it started  - but showing the game not the map… I did a reload and now it seems to be working

 �

 �

 �

 �

Dave Parkin

E:  ***@***.***> ***@***.***

M: +64274550671

 �

 �

 �

 �

 �

**Comment by MyTechnoHunter** [comment] 2023-04-30 02:31
so working now or still errors with her be dragons and scripts running long?

**Comment by Tregoen** [comment] 2023-04-30 03:07
No working fine ATM  … that seems like it was a once off…. If it happens again do you want an email with log or open a new case?

 �

 �

 �

 �

Dave Parkin

E:  ***@***.***> ***@***.***

M: +64274550671

 �

 �

 �

 �

 �

**Comment by MyTechnoHunter** [comment] 2023-04-30 03:09
new issue plese and thanks.. or you can pop into discord and make the report there..
https://discord.gg/TTUHSu7q
