### ISSUE TITLE
Bugsack spammin Questie LUA errors

### ISSUE THREAD

**Issue by soest009** [Questie/Questie#4991] opened 2023-06-23 18:39 UTC
Getting spammed by LUA errors which seem to originate from questie.
Version installed: 8.7.0
Game version: Classic WotLK 3.4.2
Bugsack report:

3011x invalid key to 'next'
[string "=[C]"]: in function `next'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:303: in function `?'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:330: in function <Questie/Modules/Quest/QuestieQuest.lua:329>

Locals:
(*temporary) = <table> {
 13610 = <table> {
 }
}
(*temporary) = 13606

Anything known about this?

Also getting: 

208x Questie/Modules/Quest/QuestieQuest.lua:746: attempt to get length of a nil value
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:746: in function `AddFinisher'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:1245: in function `PopulateObjectiveNotes'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:656: in function `GetAllQuestIds'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:483: in function <...eQuestie/Modules/Quest/QuestEventHandler.lua:480>

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:347
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:370
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:359
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1274
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:493
 SmoothReset = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:240
 PopulateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1235
 availableQuests = <table> {
 }
 UnhideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:364
 GetAllQuestIdsNoObjectives = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:669
 DrawDailyQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1636
 GetAllQuestIds = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:634
 PopulateObjective = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:866
 CompleteQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:469
 AddFinisher = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:718
 ResetAutoblacklistCategory = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:694
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1625
 UpdateQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:535
 Initialize = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1369
 SetObjectivesDirty = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:624
 ClearAllNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:199
 private = <table> {
 }
}
quest = <table> {
 startedBy = <table> {
 }
 IsTrivial = <function> defined @Questie/Database/QuestieDB.lua:677
 questFlags = 8
 level = 80
 requiredSpell = 0
 nextQuestInChain = 0
 IsRepeatable = false
 requiredClasses = 0
 questLevel = 80
 Id = 13106
 specialFlags = 0
 parentQuest = 0
 name = "Blackwatch"
 IsComplete = <function> defined @Questie/Database/QuestieDB.lua:672
 requiredLevel = 77
 objectives = <table> {
 }
 requiredSpecialization = 0
 Description = <table> {
 }
 reputationReward = <table> {
 }
 requiredRaces = 0
 ObjectiveData = <table> {
 }
 trackTimedQuest = false
 sourceItemId = 0
 Zone = 210
 LocalizedName = "Blackwatch"
 Finisher = <table> {
 }
 objectivesText = <table> {
 }
 SpecialObjectives = <table> {
 }
 finishedBy = <table> {
 }
 zoneOrSort = 210
 Starts = <table> {
 }
 preQuestSingle = <table> {
 }
 Objectives = <table> {
 }
}
questId = 13106
finisher = <table> {
 subName = ""
 questEnds = <table> {
 }
 maxLevel = 80
 maxLevelHealth = 12600
 npcFlags = 3
 zoneID = 210
 type = "monster"
 friendlyToFaction = "AH"
 id = 30631
 friendly = true
 factionID = 2050
 minLevel = 80
 minLevelHealth = 12600
 spawns = <table> {
 }
 questStarts = <table> {
 }
 name = "Darkrider Arly"
 rank = 0
}
key = "m_30631"
(*temporary) = nil
(*temporary) = <table> {
 RegisterQuestStartTooltip = <function> defined @Questie/Modules/Tooltips/Tooltip.lua:52
 lastGametooltipType = "item"
 lastGametooltip = "|cFF0070ddErathiæll, Herald of the Titans|r"
 lastFrameName = "GameTooltip"
 GetTooltip = <function> defined @Questie/Modules/Tooltips/Tooltip.lua:162
 RemoveQuest = <functi

**Comment by Dyaxler** [comment] 2023-06-24 03:05
Duplicate of #4972...

...fixed in #4981.

Will be merged with master and a new release be out soon.

**Closed by Dyaxler** 2023-06-24 03:05 UTC
Labels: Bug
