### ISSUE TITLE
lag when loading in game

### ISSUE THREAD

**Issue by Dmeercat** [Questie/Questie#2967] opened 2021-06-23 21:14 UTC
It seems as if every time I load in to wow I get lag for 5 seconds and when I hearthstone. I know its questie since I went through each addon individually.

**Comment by BreakBB** [comment] 2021-06-23 22:30
@Dmeercat Can you disable all addons except Questie, then start the profiler (`/questie` -> Advanced -> Start Profiler) and reproduce the lag by using the Hearthstone?

After you experienced the lag take a screenshot of the Profiler result and paste it here.

**Comment by Dmeercat** [comment] 2021-06-28 02:43
![image](https://user-images.githubusercontent.com/86382773/123571867-60884700-d788-11eb-9b26-09e700f0d03e.png)

**Comment by BreakBB** [comment] 2021-06-28 05:44
@Dmeercat I didn't think this through. Our profiler only records if it is open. Since you experience your lag on login the screenshot doesn't help (and also does not show anything bad).

Is your PC considered "good" or is it an old build?

Questie has to go through all quests to find out which to draw as available, complete, in progress and so on. That _could_ lead to some lag, but shouldn't really be much of a problem.

Are you using the latest version of Questie? And is the lag really bad and freezes the game for some seconds?

**Comment by Laumesis** [comment] 2021-07-31 04:02
It is something like this
 
![image](https://user-images.githubusercontent.com/75958501/127728053-46a9d861-ddad-4f82-9558-96dd4f78cb70.png)

**Comment by Laumesis** [comment] 2021-09-24 22:10
@Dmeercat How long the lag is now?
It should be improved in v6.6.2, but not fully away. I just really like to know how much stuff so far has helped situation.

**Comment by BreakBB** [comment] 2022-07-26 13:09
We made many improvements over the past month which reduced the overall performance of Questie. I will close this, but feel free to open a new report is the performance is still/again an issue.

**Closed by BreakBB** 2022-07-26 13:09 UTC
Labels: Bug
