### ISSUE TITLE
[3092] Etched Note - Not available for Troll Hunter

### ISSUE THREAD

**Issue by Likexy** [Questie/Questie#4372] opened 2022-10-08 19:49 UTC
## Description

The quest [3092] "Etched Note" is not available for **Troll Hunter**, but it shows as available via Questie.
In German the quest is called "Geätzte Notiz".

## Wowhead link

https://www.wowhead.com/wotlk/quest=3092/etched-note

## Screenshots

![InkedWoWScrnShot_100822_212756](https://user-images.githubusercontent.com/21105195/194724563-f5a54fdb-8c41-4b19-8beb-d38302baa963.jpg)
![InkedWoWScrnShot_100822_212837](https://user-images.githubusercontent.com/21105195/194724566-8e8d332b-de86-4f2e-8eda-8cf064397448.jpg)
![WoWScrnShot_100822_212840](https://user-images.githubusercontent.com/21105195/194724568-2804c29f-c1de-4dcf-9dc5-2d5f3c7ac98b.jpg)
![InkedWoWScrnShot_100822_212947](https://user-images.githubusercontent.com/21105195/194724567-245e3935-e6cc-4170-9895-4f3c2385f347.jpg)

## Questie & WoW version

WoW: WotLK
Questie: v7.3.2

Thanks & Let me know if you need any further information.
(Sorry if this isn't a bug and I wasted your time.)
Cheers

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 18:16
I just spent over an hour looking into this one and thoroughly testing.

Despite what Wowhead says - yeah, even in Classic Era, this one is Tauren-only.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 18:42
Looked into it more. This is a regression with our Wrath and TBC databases - in our Classic database this quest is correctly labelled as Tauren-only, along with all of the equivalent class quests. In our other databases, this quest is class-locked to Hunter, but listed as available for *all* Horde races. I'll issue a fix in the TBC corrections, which should then get populated to Wrath as well.

**Comment by Yttrium-tYcLief** [comment] 2022-10-27 18:50
Turns out this regression runs FAR deeper than anticipated, almost all class-locked starting zone quests (which are, in reality, race-locked to the corresponding races) are marked as all-race in our TBC database. I'll fix some neighboring values but it's possible I might not get everything.

**Closed** 2022-11-02 18:22 UTC
Labels: Questie - Quest Issue, Data Correction
