### ISSUE TITLE
Objectives for Quests Accepted in Dungeons / Raids Don't Show Until Questie Reloads

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3463] opened 2022-05-09 02:42 UTC
Grab this quest form inside Crypts. And no objectives load. Same issue with the Mag Head / KT Orb / etc.

![image](https://user-images.githubusercontent.com/55365231/167331451-4e0d34f2-1e8c-4ac3-9192-f154537dbeb2.png)

Once you reload...

![image](https://user-images.githubusercontent.com/55365231/167331603-01f2e22d-bbe0-48e6-81af-3bc52acd9424.png)

Questie is suppressing updates during Dungeons / Raids, but not refreshing properly when you leave the instance. This happens with every quest you get while in a Dungeon / Raid. 

I believe this has been an issue since the start of Classic.

**Comment by Cabro** [comment] 2022-05-09 08:55
I have also noticed this bug. It's more the fact that some quest objectives (especially ones with secondary objectives) are not redrawn when the map is reloaded (on continent switch, leaving a dungeon).

**Comment by Laumesis** [comment] 2022-07-26 12:33
These are extra objectives. Regulars should have worked fine always.
Duplicate of #3464
Fixed already in #3545

**Closed** 2022-07-26 12:38 UTC
Labels: Bug
