### ISSUE TITLE
Error during intialization

### ISSUE THREAD

**Issue by Squeaksqt** [Questie/Questie#6335] opened 2024-08-02 23:37 UTC
Currently getting an error when loading. Deleted the addon- updated the addon and still not functioning properly.

-->

Getting ERROR: Error during initialization! intereface/Addon/Questie/Modules/QuestieInit.lua:28: attempt to call method 'Initialize' (a nil value) 

![image](https://github.com/user-attachments/assets/674739a2-10e1-4ab5-8d45-71f3532f3134)
![Screenshot 2024-08-02 155730](https://github.com/user-attachments/assets/614abda0-66bc-4858-b6f9-e05398da0f6f)

I just updated to 1.15.3 Version of v10.3.9

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
Classic SOD
-->

**Comment by Squeaksqt** [comment] 2024-08-02 23:46
Tried to delete folder, delete the addon and reinstall. still this issue

**Comment by BreakBB** [comment] 2024-08-02 23:59
Duplicate of #6334

Blizzard just randomly removed an UI element Questie relied on. We are already working on a proper fix.

A workaround is here https://github.com/Questie/Questie/issues/6334#issuecomment-2266260275

**Closed by BreakBB** 2024-08-02 23:59 UTC
Labels: Bug
