### ISSUE TITLE
zoneDB.lua:215 attempt to index loacl 'questsToSplit' (a nil value)

### ISSUE THREAD

**Issue by alexander-m-ivanov** [Questie/Questie#3429] opened 2022-05-01 07:36 UTC
Hello,

the following message appeared today after I played for over a month using questie:

`zoneDB.lua:215 attempt to index loacl 'questsToSplit' (a nil value)`

The only thing I did was to log in to retail WOW and then to classic WOW. I did not try to load them at the same time.

The effect of the issue is that questie is not loading at all. I cannot use it. I tried deleting the old files and installing it anew, but it did not work. I am using the latest verison of questie: 6.9.0

**Comment by Jazzman1976** [comment] 2022-05-01 08:01
I have the same bug. Comes out of nowhere.

**Comment by MatthewANormand** [comment] 2022-05-01 08:01
I am having the same problem. Just happened randomly. Now my questie wont work at all. Please some help.

**Comment by BreakBB** [comment] 2022-05-01 08:15
Hey there,

This is a duplicate of #3426 - Check that issue for a workaround.

We are already working on a real fix for this. Sorry for the trouble

**Closed** 2022-05-01 16:33 UTC
Labels: Bug
