### ISSUE TITLE
Settings refactor

### ISSUE THREAD

**Issue by Velarax** [Questie/Questie#3458] opened 2022-05-08 20:45 UTC
Will you PLEASE either make the announce account wide OR disable it by default?  Addons like Questie Shutup should NOT be necessary.

**Comment by BreakBB** [comment] 2022-05-08 21:55
What do you mean by "the announce"? :Sweat_smile:

**Comment by Road-block** [comment] 2022-05-08 21:59
I'm guessing he means the `Announce quest updates` options in the General tab.

**Comment by BreakBB** [comment] 2022-05-08 22:05
I have no clue what the "Questie shut up" addon does, an explanation would be nice for that as well.

But we are open for suggestions and will think about a change once we know what the problem is that needs to be solved.

**Comment by Road-block** [comment] 2022-05-08 22:33
He is asking for the group announce option in Questie to be set to "disabled" by default (no chat announces for quest updates) when you install Questie.

Or for the option to not be "per character" so he can toggle it off once and have it be off for every character after that.

For my part I think it's a silly request, especially the dramatics 😛 

It's not so hard to open options > navigate to `Announce quest updates via chat` and select `Disabled` in the dropdown or uncheck some/all of the Quest accepted/abandoned/completed checkboxes.

Doing that 1 time per character is not a big deal imho.

**Comment by Muehe** [comment] 2022-05-08 22:55
Ok, so this is more like three issues basically.

1. Settings per character/account
2. The setting default (spoiler, its already solved, but wait for the hidden sub issue)
3. Questie not shutting up because others have the setting enabled

For 1. that's an argument to be had, I guess we can take this issue to discuss it.

For 2. that's a duplicate of #3220 basically, and furthermore the [option already defaults to off](https://github.com/Questie/Questie/blob/a3022e56e8df40242e7f19821645b694660e9352/Modules/Options/QuestieOptionsDefaults.lua#L124-L127).

The real problem here is probably that it defaulted to on when it was introduced, then changed. But most players followed the updates, so for the majority the setting is still on, for historical reasons if you will. This could be remedied with an update, but that leads me to 3., the merits off doing that or just introducing "Questie shutup" addon as a native Questie option should be discussed over in that issue.

So back to 1.

Having options per character is favourable over having them only account wide IMHO (think raiding char versus twink, they'll want to have different settings probably). But having both options available has its merits, although it also has its downsides. Reminds me, I should add silver vs. yellow check marks on the WoW addon list to the FAQ. :smile: 

There are better solutions of course, like setting profiles. But either way it would be a major refactor.

**Comment by Velarax** [comment] 2022-05-08 22:55
My suggestion is, make the selection account-wide so that when you select the announce quest settings, you don't have to do it on every character.  No one wants that garbage popping up mid-screen.  Literally no one I have played with or grouped with likes it.  We each have to take the time to set it to disabled.  Can't you just offer an "account wide" setting option?

**Comment by Muehe** [comment] 2022-05-08 23:12
> Can't you just offer an "account wide" setting option?

Well I guess we could, but as I alluded to with the reference of the silver and yellow question marks that's just confusing. I'd personally prefer the profile route to solve this.

By default you are in a profile called default, that tracks changes to the default settings and isn't editable. If you want to change anything you implicitly copy the default profile to "Profile x", x being an iterative number, which you can later rename.

Easier to implement, use, and understand in my humble opinion.

**Comment by Road-block** [comment] 2022-05-08 23:43
In the vein of anecdotal evidence I often quest with friends and the announce is quite helpful so we don't constantly ask each other "hey how many more bladders?".

Also anecdotally I typically ask my group when it's a pug "sorry for spam if it bothers I'll turn it off". 9 out of 10 times they tell me "no leave it on, I always forget to pick up X quest item from boss".

Some few people are annoyed, I toggle it off, no big deal.

Now for the option to filter *other* people's Questie announces I do agree that has merit and if announces are prefixed with a standard `Questie` tag, it is fairly simple to implement that as a chat filter for it.

**Comment by Velarax** [comment] 2022-05-08 23:44
Please explain how to set an account wide profile with the settings I prefer.  I can't seem to find that option anywhere.  But I still don't see why this request for an "additional" account-wide setting is such a big deal to someone who knows how to write this software.

**Comment by Muehe** [comment] 2022-05-08 23:46
@Velarax There is no way right now, I'm just thinking out loud about how to best solve your problem. Still favouring the profile route, since it's implicitly account wide and easier to understand and manage.

**Comment by Gogo1951** [comment] 2022-05-09 01:58
Any plans of ever moving forward with the overhaul for settings? As @Velarax points out, the UX for the current settings is atrocious. @AeroScripts and I had played with some new designs, feel free to use those where you can.

https://github.com/Questie/Questie/issues/2511

**Comment by Velarax** [comment] 2022-05-09 16:17
I still think my suggestion of offering as an alternative to per character settings, an account-wide "questie announce" shutoff would probably be the easiest.  All members of my dungeon and raiding groups end up going through each of their characters now to shut it off every time there is a Questie update and it gets reset.  

I do appreciate the discussion but it seems such a simple solution, one previously solved by another addon called "Questie Shutup."  Apparently this simple solution no longer works.

Here is the .lua for that addon as it previously worked:

local QuestieShutUp = CreateFrame("Frame");
QuestieShutUp:RegisterEvent("PLAYER_ENTERING_WORLD");

QuestieShutUp:SetScript("OnEvent", function(self, event, arg1, arg2, arg3, arg4, arg5) QuestieShutUp_OnEvent(event, arg1, arg2, arg3, arg4, arg5) end);

function FilterFunc(self, event, msg, author, ...)

	local l10n = QuestieLoader:ImportModule("l10n");
	local raidMarker = l10n:GetUILocale() == "ruRU" and "{звезда}" or "{rt1}";

	if msg:find(raidMarker .. " Questie : ") then

		return true;
			
	end
	
end

function QuestieShutUp_OnEvent(event, arg1, arg2, arg3, arg4, arg5)

	if event == "PLAYER_ENTERING_WORLD" then
	
		ChatFrame_AddMessageEventFilter("CHAT_MSG_PARTY", FilterFunc);
		ChatFrame_AddMessageEventFilter("CHAT_MSG_PARTY_LEADER", FilterFunc);
		
		DEFAULT_CHAT_FRAME:AddMessage("[Questie ShutUp!] Loaded.");
		
	end
	
end

**Comment by Velarax** [comment] 2022-05-09 16:30
>"In the vein of anecdotal evidence I often quest with friends and the announce is quite helpful so we don't constantly ask each other "hey how many more bladders?".

Questie furnishes this information in a tooltip that advises all group members of each other's progress, making the "mid-screen completion announcement" completely unnecessary.

**Comment by Muehe** [comment] 2022-05-14 03:15
> Any plans of ever moving forward with the overhaul for settings? As Velarax points out, the UX for the current settings is atrocious. AeroScripts and I had played with some new designs, feel free to use those where you can.

@Gogo1951 In general yes, but you know how our man-power situation is like. The suggestions you made are of course partly obsolete by now, but we will use them where we can, thanks for pointing again. :+1: 

> I still think my suggestion of offering as an alternative to per character settings, an account-wide "questie announce" shutoff would probably be the easiest. [...] I do appreciate the discussion but it seems such a simple solution, one previously solved by another addon called "Questie Shutup."

@Velarax Moving all settings to being account wide or introducing an (account-wide) profile system are about the same effort, the difference is basically adding one more drop-down menu. The real problem lies in choosing the best approach, implementing it, and then testing it (especially regarding settings changes between versions).

If you want to take a dig at it you are welcome to create a PR and we will gladly help test it. If you do be aware there are some relevant unmerged changes on the [social-config](https://github.com/Questie/Questie/tree/social-config) branch at the moment.

> All members of my dungeon and raiding groups end up going through each of their characters now to shut it off every time there is a Questie update and it gets reset.

Are you saying the announce settings are turning back on upon Questie updates? Because that definitely shouldn't happen and might require creating a separate issue.

**Comment by Velarax** [comment] 2022-05-14 15:52
I am not a programmer so I won't be editing this software.

Latest update seems to have stopped resetting this setting, thanks for fixing it

**Comment by Muehe** [comment] 2022-05-17 19:40
@Velarax That's ok, but then you will have to wait until we do this on our schedule.

The setting not changing back anymore after an update is an effect of the default being changed in a recent PR, but it shouldn't change back in the first place, for which I will create a new issue.

**Comment by Velarax** [comment] 2022-05-19 19:33
Yeah update before last I had to change the setting to "disabled" on every toon.  The latest update did not change those settings.

**Closed** 2023-05-23 20:30 UTC
Labels: Refactoring
