### ISSUE TITLE
New Tracker doesn't Track Objectives with only 1 Item

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4785] opened 2023-04-24 02:44 UTC
![image](https://user-images.githubusercontent.com/55365231/233888926-2593cede-fc75-47ef-a63b-e083def8aaab.png)

I have 2 of the 4 objective items, but there's no indication that I have completed any of those objectives.

**Comment by BreakBB** [comment] 2023-04-24 05:51
Duplicate of #4781

This is a regression, because we forgot about the white coloring of the objectives in the Tracker. When chosing "red -> green" for example, then the `1/1` will be green vs. `0/1` being red.

**Closed by BreakBB** 2023-04-24 05:51 UTC
Labels: Bug
