### ISSUE TITLE
Quest Issue for quest 25476 - Rescue OOX-22/FE! (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6234] opened 2024-07-20 15:20 UTC
## Description
Questie says "Unknown Category" for this quest in the tracker, quest escort itself is in Feralas, quest hand in is in Booty Bay/Stranglethorn, might want to assign it a category.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25476/rescue-oox-22-fe

## Screenshots
Quest listed as unknown category:
![image](https://github.com/user-attachments/assets/2efc0fc2-8b31-4d06-b1a3-eb8ac7497791)

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment] 2024-09-25 08:09
@Cabro duplicate of https://github.com/Questie/Questie/issues/5975 which is fixed - please can you close this

**Closed** 2024-09-25 08:14 UTC
Labels: Data Correction, cata
