### ISSUE TITLE
noblegarden event

### ISSUE THREAD

**Issue by Druidimies** [Questie/Questie#4890] opened 2023-05-13 14:38 UTC
questie started to say that noblegarden event is active today. 13.5.2023.
wotlk classic,

**Comment by kbspammage** [comment] 2023-05-13 22:33
![image](https://github.com/Questie/Questie/assets/133543776/636b5c90-22a9-40cf-8995-723f785a8287)
I have had this for a few days now as well and have tried to fix it via advanced in-game options; reset and recompile the database.

**Comment by vgullotta8** [comment] 2023-05-15 21:32
I also have the Noblegarden event is active bug

**Comment by MyTechnoHunter** [comment] 2023-05-15 22:34
not a bug, just needs a correction for date/time, it fluctuates..

**Comment by vgullotta8** [comment] 2023-05-15 22:35
is that something I can do?

**Comment by hattrickpatrick** [comment] 2023-05-16 22:45
Also having this issue.

**Comment by BreakBB** [comment] 2023-05-22 20:56
This was fixed in 0fed31165c44616fa0377db1c2b06858273b90ff

**Closed by BreakBB** 2023-05-22 20:56 UTC
Labels: Bug
