### ISSUE TITLE
PVP Quests Showing When Unselected

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6445] opened 2024-10-02 01:42 UTC
Classic Era

<img width="453" alt="image" src="https://github.com/user-attachments/assets/7da0cbdc-c63e-4509-9514-e64336a4c320">

But PVP is turned off.

<img width="514" alt="image" src="https://github.com/user-attachments/assets/c19ef2db-b482-403f-bc9b-6f8df49e154d">

**Comment by BreakBB** [comment] 2024-10-02 06:21
It looks like https://www.wowhead.com/classic/quest=8386/fight-for-warsong-gulch is not marked as PvP quest on Blizzards side.

`/dump GetQuestTagInfo(8386)` returns `nil` while it should return `{41, "PvP"}`.

To fix this we need to override the API result here:

https://github.com/Questie/Questie/blob/990dab9c7f49f50058f42b3f6e50b691557e5cfb/Database/QuestieDB.lua#L61

**Comment by Gogo1951** [comment] 2024-10-05 00:15
Happening for more than that one quest. Just an FYI. Seems to be all the PVP quests in Classic Era. All that I have access too anyway at 28 seem to show.

<img width="412" alt="image" src="https://github.com/user-attachments/assets/dbd716f5-7e95-4c3f-be07-99226add7ec8">

**Comment by BreakBB** [comment] 2024-10-08 08:04
@Gogo1951 can you enable Quest IDs and share the IDs as well? At least for "Fight for Warsong Gulch" I can not reproduce this:

![image](https://github.com/user-attachments/assets/21d363db-071f-4d90-aa30-0ef0fa62d7d8)

**Comment by BreakBB** [comment] 2024-10-08 08:22
Hmmm... I noticed something on the Arathi Basin quest though. We are using an API function to check if a quest is PvP or not and it seems that data needs to be cached on client side. That means when calling that API for the first time it can return `nil` while it returns correct data on the second call.

**Comment by Gogo1951** [comment] 2024-10-30 02:40
Back again. =P

<img width="390" alt="image" src="https://github.com/user-attachments/assets/fc5e22d6-776f-4190-889e-d0d1f645697d">

**Comment by Gogo1951** [comment] 2024-11-10 20:31
Seems fixed now.

**Comment by BreakBB** [comment] 2024-11-10 23:31
This is bot fixed, just something that doesn't always occur

**Comment by BreakBB** [comment] 2024-11-28 10:26
This is now fixed in 9b61727735d11613a7b9b3b4e4bde34f687cd0d4 and will be shipped in the next release.

**Closed by BreakBB** 2024-11-28 10:26 UTC
Labels: Bug, Module - Database, Module - Map / Minimap, era/hc/anniversary
