### ISSUE TITLE
Double Link Color Bug

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3763] opened 2022-07-20 20:33 UTC
![image](https://user-images.githubusercontent.com/55365231/180076300-efb9d0c1-5cfc-43a7-b3b4-e28a32ae3232.png)

Brackets on Dailies should be Blue too.

**Comment by BreakBB** [comment] 2022-07-20 20:45
Duplicate of #3655

**Closed by BreakBB** 2022-07-20 20:45 UTC
Labels: Bug
