### ISSUE TITLE
Questie fails initialization: Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Modules/QuestieInit.lua:281: attempt to call method 'Initialize' (a nil value)

### ISSUE THREAD

**Issue by laur0511** [Questie/Questie#6339] opened 2024-08-02 23:56 UTC
## Bug description

Questie doesn't initialize, with the error
Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Modules/QuestieInit.lua:281: attempt to call method 'Initialize' (a nil value)

## Screenshots
![image](https://github.com/user-attachments/assets/1d4f50e9-b4e6-4568-b5fb-6c9ae4f2b2ad)

## Questie & WoW version
10.3.9
SoD

I tried deleting all the data, reinstalling, even disabling every other addon except questie and still cannot get it fixed. I reinstalled it manually and thru curse, deleted all the data in WTF, but it always returns the same error. I also tried removing my whole WTF folder, still nothing

**Comment by fuzzyhutch** [comment] 2024-08-02 23:59
![questie](https://github.com/user-attachments/assets/43057aaf-b01b-430f-a700-8d4c08c1d406)

**Comment by BreakBB** [comment] 2024-08-02 23:59
Duplicate of #6334

Blizzard just randomly removed an UI element Questie relied on. We are already working on a proper fix.

A workaround is here https://github.com/Questie/Questie/issues/6334#issuecomment-2266260275

**Comment by mykeylikesit** [comment] 2024-08-02 23:59
im having the same issue </3

**Closed by BreakBB** 2024-08-02 23:59 UTC
Labels: Bug

**Comment by mykeylikesit** [comment] 2024-08-03 00:01
![Screenshot 2024-08-02 170100](https://github.com/user-attachments/assets/9e17d7da-3a3b-4feb-a52a-e903a628f3ff)
