### ISSUE TITLE
Questie Auto Accepting quests from npcs

### ISSUE THREAD

**Issue by Vallravn** [Questie/Questie#5979] opened 2024-05-15 20:27 UTC

**Comment by MyTechnoHunter** [comment] 2024-05-15 21:03
This is not question this is actually blizzard they have made it so that starting quests in most starting zones specifically for the new races as well are Auto accepted

**Comment by BreakBB** [comment] 2024-05-16 04:43
Duplicate of #5965 and #5970

The next update will include a fix, so that the quest frame will no longer close. Accepting itself is, as TechnoHunter already said, done by Blizzard.

**Closed by BreakBB** 2024-05-16 04:43 UTC
Labels: Bug
