### ISSUE TITLE
Questie: [ERROR] Error during initialization! Interface\AddOns\Questie\Database\Zones\zoneDB.lua:215: attempt to index local 'questsToSplit' (a nil value)

### ISSUE THREAD

**Issue by baaatzi** [Questie/Questie#3432] opened 2022-05-01 08:35 UTC
Hi,
I am playing Season of Mastery and since the last update I receive the following error message during initialization:

"Questie: [ERROR] Error during initialization! Interface\AddOns\Questie\Database\Zones\zoneDB.lua:215: attempt to index local 'questsToSplit' (a nil value)"

I tryed reinstalling and also installing older questie version, but it is still not working.
As a result questie is not showing any quest objectives ingame.

Hope you can fix it.
Thanks a lot.

**Comment by BreakBB** [comment] 2022-05-01 08:37
This is a duplicate of #3426 and #3429

Check the first one for a workaround. We are already working on a proper fix which we will release later today.

**Closed by BreakBB** 2022-05-01 08:37 UTC
Labels: Bug
