### ISSUE TITLE
Questie Initialization Error

### ISSUE THREAD

**Issue by carcharodonc** [Questie/Questie#6344] opened 2024-08-03 00:35 UTC
## Bug description

Every time I log in, the error message below pops up and the addon does not work. I've tried reinstalling it and tried the previous version (v10.3.8) and was still getting the error.

## Screenshots

![error](https://github.com/user-attachments/assets/2750159c-5b6e-4c42-ace4-f229b602dd27)

## Questie & WoW version

Classic Era
Questie v10.3.9

**Comment by BreakBB** [comment] 2024-08-03 00:36
Duplicate of #6334 

This version fixes the issue: https://github.com/Questie/Questie/releases/tag/v10.3.10

CurseForge needs a few more minutes.

**Comment by HotButteredRum** [comment] 2024-08-03 00:36
Same, trying to play classic and questie is not working.  This is the error I am getting:
![image](https://github.com/user-attachments/assets/15a1df9e-f592-4ed3-81fc-b1c2fdaadad6)

**Comment by carcharodonc** [comment] 2024-08-03 00:37
Ah, thank you! I use curseforge so that seems to be why!

**Closed by BreakBB** 2024-08-03 00:36 UTC
Labels: Bug
