### ISSUE TITLE
Editing LFG note causes interface error

### ISSUE THREAD

**Issue by davidm88** [Questie/Questie#4822] opened 2023-04-28 07:22 UTC
## Bug description
1. Queue for something in LFG.
2. Edit the note and click update.
3. LFG UI is just stuck on "Searching..." now. Error in chat log "Interface action failed because of an AddOn
4. Taint log:
`4/28 17:15:48.450  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by Questie - Interface/FrameXML/UIDropDownMenu.lua:40
4/28 17:15:48.450      securecall()
4/28 17:15:48.450      Interface/FrameXML/UIDropDownMenu.lua:74 UIDropDownMenu_Initialize()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:169 LFGBrowseFrame:SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:69
4/28 17:15:48.450  Execution tainted by Questie while reading UIDROPDOWNMENU_MENU_LEVEL - Interface/FrameXML/UIDropDownMenu.lua:902 UIDropDownMenu_GetSelectedID()
4/28 17:15:48.450      Interface/FrameXML/UIDropDownMenu.lua:776 UIDropDownMenu_Refresh()
4/28 17:15:48.450      Interface/FrameXML/UIDropDownMenu.lua:881 UIDropDownMenu_SetSelectedValue()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:170 LFGBrowseFrame:SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:69
4/28 17:15:48.450  An action was blocked because of taint from Questie - Search()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:226 LFGBrowse_DoSearch()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:179 LFGBrowseFrame:SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
4/28 17:15:48.450      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:69
`

## Screenshots
![image](https://user-images.githubusercontent.com/2033527/235081511-59104877-1572-4a42-856d-20d447c194f5.png)

## Questie & WoW version
WoW: 3.4.1 (49345) (Release x64)
Questie: v8.0.1

**Comment by BreakBB** [comment] 2023-04-28 10:09
Hey @davidm88 thanks for reporting this. I'll mark this as duplicate of #4814 - A fix is already in the pipeline and we're testing it.

**Closed by BreakBB** 2023-04-28 10:09 UTC
Labels: Bug
