### ISSUE TITLE
Questie Error - Classic SoM

### ISSUE THREAD

**Issue by Laithel** [Questie/Questie#3433] opened 2022-05-01 09:14 UTC
Hello,

I have an error with questie. The error appeared spontaneously upon logging back into my main character after briefly playing on an alt. Questie had worked fine this same morning. The error text is as follows, and appears immediately upon logging in:

Questie: [ERROR] Error during initialization!
    Interface\AddOns\Questie\Database\Zones\zone
    DB.lua:215: attempt to index local 'questsToSplit'
    (a nil value)
    
I have attempted the following to fix this:
> Uninstall and reinstall questie
> Uninstall questie and installed the previous version
> Deleted the lua and lua.bak folders from my character(s) then reloaded

Any help would be appreciated.

**Comment by BreakBB** [comment] 2022-05-01 09:23
This is a duplicate of #3426 and #3429

Check the first one for a workaround. We are already working on a proper fix which we will release later today.

**Comment by Laithel** [comment] 2022-05-01 09:23
Thankyou kindly

**Closed by BreakBB** 2022-05-01 09:23 UTC
Labels: Bug
