### ISSUE TITLE
WOTLK: Move mouse over need/greed/pass causes questie to error out and get caught in bugsack

### ISSUE THREAD

**Issue by wazerstar** [Questie/Questie#5017] opened 2023-07-04 07:14 UTC
## Bug description
Every time I move my mouse over items in bags or in tooltips from bis-tooltip i can happen randomly, but items that you need to need/greed/pass on, it will popup each time 100%

## Screenshots
[Picture](https://i.imgur.com/MSQCMes.png)

## Error Code
```
182x ...ceQuestie/Modules/Tracker/QuestieTracker.lua:429: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:429: in function `QuestItemLooted'
[string "@Questie/Modules/QuestieEventHandler.lua"]:175: in function <...rfaceQuestie/Modules/QuestieEventHandler.lua:174>
[string "=[C]"]: ?
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>


Locals:
(*temporary) = nil
```

## Questie & WoW version
Questie 8.8.1
WoW: Wotlk

**Comment by BreakBB** [comment] 2023-07-04 07:34
Hey @wazerstar can you disable all addons except Questie and verify this is still an issue?

It might be another addon with a broken "Ace" library, that results in this error. In the stack trace ElvUI is noted to deliver the Ace library this time.

**Comment by wazerstar** [comment] 2023-07-04 10:47
> Hey @wazerstar can you disable all addons except Questie and verify this is still an issue?
> 
> It might be another addon with a broken "Ace" library, that results in this error. In the stack trace ElvUI is noted to deliver the Ace library this time.

I wont be playing PVE without elvui so you are saying it could be elvui fault?

I'm playing with elvui pr default, cant really play without it, I guess I can try delete questie total and reinstall including its settings.

Will have to get back with that, depending on your answer.

**Comment by BreakBB** [comment] 2023-07-04 11:41
Honestly, it could by any addon and I doubt it really is ElvUI. It might also be some weird edge case in Questie, can't tell by just the stack trace, we need to dive deeper.

Maybe @Dyaxler @MyTechnoHunter or @Yttrium-tYcLief have an idea what could be the root cause.

**Comment by wazerstar** [comment] 2023-07-04 11:42
> Honestly, it could by any addon and I doubt it really is ElvUI. It might also be some weird edge case in Questie, can't tell by just the stack trace, we need to dive deeper.
> 
> Maybe @Dyaxler @MyTechnoHunter or @Yttrium-tYcLief have an idea what could be the root cause.

btw forgot to mention I get this occasionally and now its all the time when I start or reload the game.

https://i.imgur.com/LQpqp1b.png

**Comment by Dyaxler** [comment] 2023-07-04 17:11
Yeah, this is somewhat related to the other bug that was filled. The fix for this should be in my PR.

**Comment by Dyaxler** [comment] 2023-07-04 19:09
REF: https://github.com/Questie/Questie/pull/5013

**Comment by Muehe** [comment] 2023-07-04 20:16
@wazerstar We had the same report on Discord recently, the offending addon was AtlasLoot (possibly in connection with Attune being active). Updating the Ace3 version (https://www.curseforge.com/wow/addons/ace3/files/4040413) in AtlasLoot might solve the error, but we didn't get feedback on that.

If it's not one of those two addons the way to find the offending addon is to enable just Questie, and then re-enable addons (or batches of them) one by one until the error is back.

Also not sure what is going on with the reload error, it's usually *solved* by reloading when it happens (which should be veeeeery occasionally). :see_no_evil: Anyway it's a separate problem, so I'll move it to another issue.

**Closed** 2023-07-16 14:40 UTC
Labels: Bug, Module - Tracker
