### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Feronas** [Questie/Questie#5003] opened 2023-06-28 14:28 UTC
## Bug description
Lua Error Randomly popped up while flying in Wintergraps.

Also confirmed the error pops up when getting summoned into Wintergrasp.

## Screenshots
![image](https://github.com/Questie/Questie/assets/65334149/29d815eb-1c14-4dd2-bf25-d69f9e1a2de0)

## Questie & WoW version

![image](https://github.com/Questie/Questie/assets/65334149/f493120d-79c2-4a53-a835-ef19d44b348c)

Wotlk.

**Comment by GregoryGH** [comment] 2023-06-28 16:32
same. sometimes spam a lot

2x Questie/Modules/Quest/QuestieQuest.lua:751: attempt to index a nil value
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:751: in function `AddFinisher'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:1229: in function `PopulateObjectiveNotes'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:659: in function `GetAllQuestIds'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:542: in function <...eQuestie/Modules/Quest/QuestEventHandler.lua:539>

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:347
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:371
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:359
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1245
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:494

**Comment by Dyaxler** [comment] 2023-06-28 18:15
Duplicate of #4999 

This fix has been checked into Master but has not been pushed out to another release yet...

**Closed by Dyaxler** 2023-06-28 18:15 UTC
Labels: Bug
