### ISSUE TITLE
Got error on my mac. The addon is not launching. Wrath classic. Thank you :) 

### ISSUE THREAD

**Issue by smiler2809** [Questie/Questie#4642] opened 2023-02-03 17:03 UTC
<img width="453" alt="Screenshot 2023-02-03 at 19 03 29" src="https://user-images.githubusercontent.com/36519763/216663253-352e49fc-44e9-48b2-a035-2aae5a52b89a.png">

**Comment by Muehe** [comment] 2023-02-03 17:19
Hey @smiler2809 , the error message indicates that you have to update or something went wrong during an update. You can try manually deleting Questie directory in `Interface/AddOns` and then re-installing from a fresh download, or choosing the "Reinstall" option if you use an addon manager like the Curseforge app.

**Comment by Muehe** [comment] 2023-02-04 11:10
@MyTechnoHunter In this case it has got nothing to do with SavedVariables, it's a broken update. As you can see when comparing the lines in the error to our current code, they contain different code now: [AceGUIContainer-Frame.lua#L193](https://github.com/Questie/Questie/blob/master/Libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua#L193) [QuestieOptions.lua#L46](https://github.com/Questie/Questie/blob/master/Modules/Options/QuestieOptions.lua#L46)

In particular calls to `SetMinResize` were changed in WoW release 3.4.1 (for WotLK only, not for Era) and fixed in Questie release 7.4.6 (all calls were changed to `QuestieCompat.SetResizeBounds`). All the bugs I have seen with it so far have been broken updates using old code.

@smiler2809 @Ouchsorryz Please make sure you addon list on the character selection screen shows Questie version 7.4.6 or greater.

**Comment by Ouchsorryz** [comment] 2023-02-04 15:02
The problem is fixed.  i downloaded version 7.4.12 and manually installed it into my addons folder after completely deleting questie from folder. Open game and it still says version 7.4.5. yes, it was the correct addon folder as when i deleted questie i opened
 game and saw it was gone from addon list.   i then used curse addon to install updates and everything is working as intended.  not sure why it wasn't recognizing the new version but it works.   Thanks for the time folks, i truly appreciate it.

**Comment by Muehe** [comment] 2023-02-06 23:38
Assumed resolved. @smiler2809 Please let us know if you require any further assistance.

**Closed by Muehe** 2023-02-06 23:38 UTC
Labels: Bug
