### ISSUE TITLE
The New Questie Reset My Settings

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4629] opened 2023-01-29 03:01 UTC
Something with the new Questie reset the nameplate settings. 

Moved icons around to new locations.

This was the only setting reset. I noticed because all of a sudden I had marks on my target an I always turn those off.

![image](https://user-images.githubusercontent.com/55365231/215302122-9ee70ac0-2d51-4cfa-a9eb-5cc8427eb39d.png)

**Comment by Muehe** [comment] 2023-01-31 22:43
Duplicate of #3495 

Made new labels since then, so added them to that issue (thanks for the reminder :sweat_smile: ).

Also this would probably be resolved by switching settings to profiles instead of the unholy mess we have now, which I don't recall the issue number(s) off atm. It's on The List™.

**Closed by Muehe** 2023-01-31 22:43 UTC
Labels: Bug
