### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tstanley32** [Questie/Questie#2948] opened 2021-06-14 02:27 UTC
I am using the latest version. On one char on TBC I get the message error the quest 9215, 9156, 9627 is missing in questions data base please report this on GitHub or discord 

Hello, thanks for taking the time to report a bug!

Before you proceed, please verify that you're running the latest version of Questie. The easiest way to do this is via the Twitch client, but you can also download the latest version here: https://www.curseforge.com/wow/addons/questie

Questie is one of the most popular Classic WoW addons, with over 22M downloads. However, like almost all WoW addons, it's built and maintained by a team of volunteers. The current Questie team is:

* @AeroScripts / Aero#1357 (Discord)
* @BreakBB / TheCrux#1702 (Discord)
* @drejjmit / Drejjmit#8241 (Discord)
* @Dyaxler / Dyaxler#0086 (Discord)
* @gogo1951 / Gogo#0298 (Discord)

If you'd like to help, please consider making a donation. You can do so here: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=aero1861%40gmail%2ecom&lc=CA&item_name=Questie%20Devs&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted

You can also help as a tester, developer or translator, please join the Questie Discord here https://discord.gg/fYcQfv7

-->

**Comment by drejjmit** [comment] 2021-06-14 06:23
Duplicate of #2938

**Closed by drejjmit** 2021-06-14 06:23 UTC
Labels: Type - Defect
