### ISSUE TITLE
Disarm/Broken Weapon/Item Type Disconnect

### ISSUE THREAD

**Issue by ChandlerFerry** [Questie/Questie#4045] opened 2022-09-05 17:30 UTC
## Bug description
Upon being disarmed or having a broken weapon, there is a very notable chance of you disconnecting to the login screen in the middle of combat.

Also seems to happen if you switch from a one archetype, e.g. sword to another, e.g. mace/axe in a dungeon
  - Fixes itself after some period of time, easiest was to hearth to town, vendor, repair, etc.

Unfortunately, there is no lua error due to it causing a disconnect (unless there is one written to a log?)

## Screenshots
![Inventory](https://user-images.githubusercontent.com/3268868/188495258-06aa4a77-a036-446f-a9cb-12dfd302063d.png)
![Hit wolf](https://user-images.githubusercontent.com/3268868/188495280-cc9556cd-1e75-4cef-a793-fb06b514b05d.png)
![Disconnect](https://user-images.githubusercontent.com/3268868/188495292-668f193f-f591-431e-a1bd-8231f99e6492.png)

## Questie & WoW version
Questie v7.0.1

WotLK Classic

**Comment by submarines-and** [comment] 2022-09-05 18:17
I am experiencing something similar. Any time I increase a skill (engineering, unarmed, axes) there is a high chance of disconnection.

I have tracked it down to questie causing it, but I do not understand why. Does questie do anything with the chat log maybe?

**Comment by BreakBB** [comment] 2022-09-05 18:19
Hey @ChandlerFerry and @submarines-and yes Questie checks for new available quests on skill levelup (should only be crafting skill level not weapon skill level). This is needed because some quests have a crafting requirement.

We don't understand the disconnect part though as you can read in #3987

**Comment by submarines-and** [comment] 2022-09-05 18:21
Sorry, missed that this was a duplicate issue!

**Comment by ChandlerFerry** [comment] 2022-09-05 18:22
It's technically not a duplicate cause, appears to have the same effect.

That being said, if the source is `possibly provoking something on Blizzards side`, then it's out of scope regardless.

**Comment by BreakBB** [comment] 2022-09-05 18:25
We think it is the same source cause these disconnects. Because quest turn in as well as skill level up calculates the available quests.

But again: We can't say much about the root cause yet, sorry 🙈

**Comment by submarines-and** [comment] 2022-09-05 18:44
I can force myself offline by levelling a one handed (read: fast) weapon skill many times in a short time span, When using a 2 hander, I stay online. Maybe there is some throttling, as someone suggested in the other thread.

Now I am speculating, but this would explain why it never happens during normal play, since skillups are quite spaced out.

**Comment by submarines-and** [comment] 2022-09-05 18:51
I have maces left to level, so let me know if there is a debug flag / option you want me to test.

**Comment by BreakBB** [comment] 2022-09-05 18:53
@submarines-and check the last comment in #3987 - Would be nice if you disable the "Comms module" and check again for a bit.

**Comment by submarines-and** [comment] 2022-09-05 19:03
Still disconnects. Attaching a video that shows the frequency of skill ups.

https://imgur.com/NfBm1Xr

Setting made:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/3114694/188502866-111a3e26-76dd-4066-8b3d-f3f396eb8a39.png">

**Comment by BreakBB** [comment] 2022-09-07 05:20
Hey @ChandlerFerry could you also test the version linked here and see if that helps? https://github.com/Questie/Questie/issues/3987#issuecomment-1238618174

**Comment by BreakBB** [comment] 2022-10-07 08:42
Closing this in favor of #3987

**Closed by BreakBB** 2022-10-07 08:42 UTC
Labels: Bug
